# GENERATED FILE - do not edit by hand.
# Regenerate with: python modules/archipelago_wow/tools/generate_content.py content/gates.yaml


ITEMS: dict[str, tuple[int, int]] = {
    "Progressive Riding: Apprentice": (830000, 1),
    "Progressive Riding: Journeyman": (830001, 1),
    "Progressive Riding: Expert": (830002, 1),
    "Progressive Riding: Artisan": (830003, 1),
    "Progressive Riding: Cold Weather Flying": (830004, 1),
    "Flight Unlock: Outland": (830005, 1),
    "Flight Unlock: Northrend": (830006, 1),
    "Armor Proficiency: Plate": (830007, 1),
    "Armor Proficiency: Mail": (830008, 1),
    "Armor Proficiency: Leather": (830009, 1),
    "Weapon Proficiency: Two-Handed Swords": (830010, 1),
    "Weapon Proficiency: Axes": (830011, 1),
    "Weapon Proficiency: Maces": (830012, 1),
    "Weapon Proficiency: Staves": (830013, 1),
    "Weapon Proficiency: Wands": (830014, 1),
    "Auction House Access": (830015, 1),
    "Hearthstone Access": (830016, 1),
    "Mailbox Access": (830017, 1),
    "Bank Access": (830029, 1),
    "Gathering Access": (830030, 1),
    "Progressive Bank Bag Slot: Slot 1": (830018, 1),
    "Progressive Bank Bag Slot: Slot 2": (830019, 1),
    "Progressive Bank Bag Slot: Slot 3": (830020, 1),
    "Progressive Bank Bag Slot: Slot 4": (830021, 1),
    "Progressive Bank Bag Slot: Slot 5": (830022, 1),
    "Progressive Bank Bag Slot: Slot 6": (830023, 1),
    "Progressive Bank Bag Slot: Slot 7": (830024, 1),
    "Talent Point Access": (830025, 1),
    "Dual Spec Unlock": (830026, 1),
    "Progressive Glyph Slot: Slot 1": (830031, 1),
    "Progressive Glyph Slot: Slot 2": (830032, 1),
    "Progressive Glyph Slot: Slot 3": (830033, 1),
    "Progressive Glyph Slot: Slot 4": (830034, 1),
    "Progressive Glyph Slot: Slot 5": (830035, 1),
    "Progressive Glyph Slot: Slot 6": (830036, 1),
    "TBC Combo Unlock": (830027, 1),
    "WotLK Combo Unlock": (830028, 1),
}

FLAG_KEY_BY_ITEM_NAME: dict[str, str] = {
    "Progressive Riding: Apprentice": "riding",
    "Progressive Riding: Journeyman": "riding",
    "Progressive Riding: Expert": "riding",
    "Progressive Riding: Artisan": "riding",
    "Progressive Riding: Cold Weather Flying": "riding",
    "Flight Unlock: Outland": "flight",
    "Flight Unlock: Northrend": "flight",
    "Armor Proficiency: Plate": "proficiency_armor_plate",
    "Armor Proficiency: Mail": "proficiency_armor_mail",
    "Armor Proficiency: Leather": "proficiency_armor_leather",
    "Weapon Proficiency: Two-Handed Swords": "proficiency_weapon_2h_sword",
    "Weapon Proficiency: Axes": "proficiency_weapon_axe",
    "Weapon Proficiency: Maces": "proficiency_weapon_mace",
    "Weapon Proficiency: Staves": "proficiency_weapon_staff",
    "Weapon Proficiency: Wands": "proficiency_weapon_wand",
    "Auction House Access": "access_auction_house",
    "Hearthstone Access": "access_hearth",
    "Mailbox Access": "access_mailbox",
    "Bank Access": "access_bank",
    "Gathering Access": "access_gathering",
    "Progressive Bank Bag Slot: Slot 1": "bank_bag_slots",
    "Progressive Bank Bag Slot: Slot 2": "bank_bag_slots",
    "Progressive Bank Bag Slot: Slot 3": "bank_bag_slots",
    "Progressive Bank Bag Slot: Slot 4": "bank_bag_slots",
    "Progressive Bank Bag Slot: Slot 5": "bank_bag_slots",
    "Progressive Bank Bag Slot: Slot 6": "bank_bag_slots",
    "Progressive Bank Bag Slot: Slot 7": "bank_bag_slots",
    "Talent Point Access": "access_talent_points",
    "Dual Spec Unlock": "dual_spec",
    "Progressive Glyph Slot: Slot 1": "glyph_slots",
    "Progressive Glyph Slot: Slot 2": "glyph_slots",
    "Progressive Glyph Slot: Slot 3": "glyph_slots",
    "Progressive Glyph Slot: Slot 4": "glyph_slots",
    "Progressive Glyph Slot: Slot 5": "glyph_slots",
    "Progressive Glyph Slot: Slot 6": "glyph_slots",
    "TBC Combo Unlock": "combo_unlock_tbc",
    "WotLK Combo Unlock": "combo_unlock_wotlk",
}

FLAG_TIER_BY_ITEM_NAME: dict[str, int] = {
    "Progressive Riding: Apprentice": 1,
    "Progressive Riding: Journeyman": 2,
    "Progressive Riding: Expert": 3,
    "Progressive Riding: Artisan": 4,
    "Progressive Riding: Cold Weather Flying": 5,
    "Flight Unlock: Outland": 1,
    "Flight Unlock: Northrend": 2,
    "Armor Proficiency: Plate": 1,
    "Armor Proficiency: Mail": 1,
    "Armor Proficiency: Leather": 1,
    "Weapon Proficiency: Two-Handed Swords": 1,
    "Weapon Proficiency: Axes": 1,
    "Weapon Proficiency: Maces": 1,
    "Weapon Proficiency: Staves": 1,
    "Weapon Proficiency: Wands": 1,
    "Auction House Access": 1,
    "Hearthstone Access": 1,
    "Mailbox Access": 1,
    "Bank Access": 1,
    "Gathering Access": 1,
    "Progressive Bank Bag Slot: Slot 1": 1,
    "Progressive Bank Bag Slot: Slot 2": 2,
    "Progressive Bank Bag Slot: Slot 3": 3,
    "Progressive Bank Bag Slot: Slot 4": 4,
    "Progressive Bank Bag Slot: Slot 5": 5,
    "Progressive Bank Bag Slot: Slot 6": 6,
    "Progressive Bank Bag Slot: Slot 7": 7,
    "Talent Point Access": 1,
    "Dual Spec Unlock": 1,
    "Progressive Glyph Slot: Slot 1": 1,
    "Progressive Glyph Slot: Slot 2": 2,
    "Progressive Glyph Slot: Slot 3": 3,
    "Progressive Glyph Slot: Slot 4": 4,
    "Progressive Glyph Slot: Slot 5": 5,
    "Progressive Glyph Slot: Slot 6": 6,
    "TBC Combo Unlock": 1,
    "WotLK Combo Unlock": 1,
}
