# GENERATED FILE - do not hand-edit.
# Regenerate with: python tools/extract_instance_entrances.py (from azerothcore-wotlk/modules/archipelago_wow)
from __future__ import annotations

INSTANCE_ENTRANCE_AREA_TAGS: dict[str, frozenset[str]] = {
    'ahn_kahet_the_old_kingdom': frozenset({'dragonblight'}),
    'ahn_qiraj_temple': frozenset({'silithus'}),
    'auchindoun_auchenai_crypts': frozenset({'nagrand', 'terokkar_forest'}),
    'auchindoun_mana_tombs': frozenset({'nagrand', 'terokkar_forest'}),
    'auchindoun_sethekk_halls': frozenset({'terokkar_forest'}),
    'auchindoun_shadow_labyrinth': frozenset({'terokkar_forest'}),
    'azjol_nerub': frozenset({'dragonblight'}),
    'battle_for_mount_hyjal': frozenset({'tanaris'}),
    'black_temple': frozenset({'shadowmoon_valley'}),
    'blackfathom_deeps': frozenset({'ashenvale', 'darkshore', 'felwood'}),
    'blackrock_depths': frozenset({'burning_steppes', 'searing_gorge'}),
    'blackrock_spire': frozenset({'burning_steppes', 'searing_gorge'}),
    'coilfang_serpentshrine_cavern': frozenset({'blade_s_edge_mountains', 'zangarmarsh'}),
    'coilfang_the_slave_pens': frozenset({'zangarmarsh'}),
    'coilfang_the_steamvault': frozenset({'blade_s_edge_mountains', 'zangarmarsh'}),
    'coilfang_the_underbog': frozenset({'zangarmarsh'}),
    'culling_of_stratholme': frozenset({'tanaris'}),
    'deadmines': frozenset({'stranglethorn_vale', 'westfall'}),
    'dire_maul': frozenset({'barrens', 'feralas', 'mulgore'}),
    'drak_tharon_keep': frozenset({'grizzly_hills', 'zul_drak'}),
    'escape_from_durnholde': frozenset({'tanaris'}),
    'eye_of_eternity': frozenset({'borean_tundra'}),
    'forge_of_souls': frozenset({'icecrown', 'wintergrasp'}),
    'gnomeregan': frozenset({'dun_morogh'}),
    'gruul_s_lair': frozenset({'blade_s_edge_mountains', 'netherstorm'}),
    'gundrak': frozenset({'storm_peaks', 'zul_drak'}),
    'halls_of_lightning': frozenset({'storm_peaks'}),
    'halls_of_reflection': frozenset({'icecrown', 'wintergrasp'}),
    'halls_of_stone': frozenset({'storm_peaks'}),
    'hellfire_citadel_ramparts': frozenset({'hellfire_peninsula'}),
    'hellfire_citadel_the_blood_furnace': frozenset({'hellfire_peninsula'}),
    'hellfire_citadel_the_shattered_halls': frozenset({'hellfire_peninsula'}),
    'icecrown_citadel': frozenset({'icecrown'}),
    'karazhan': frozenset({'blasted_lands', 'deadwind_pass'}),
    'magister_s_terrace': frozenset({'isle_of_quel_danas'}),
    'magtheridon_s_lair': frozenset({'hellfire_peninsula'}),
    'maraudon': frozenset({'barrens', 'desolace'}),
    'molten_core': frozenset({'burning_steppes', 'searing_gorge'}),
    'naxxramas': frozenset({'dragonblight', 'grizzly_hills'}),
    'nexus': frozenset({'borean_tundra'}),
    'obsidian_sanctum': frozenset({'dragonblight'}),
    'oculus': frozenset({'borean_tundra'}),
    'onyxia_s_lair': frozenset({'barrens', 'dustwallow_marsh', 'thousand_needles'}),
    'opening_of_the_dark_portal': frozenset({'tanaris'}),
    'pit_of_saron': frozenset({'icecrown', 'wintergrasp'}),
    'ragefire_chasm': frozenset({'orgrimmar'}),
    'razorfen_downs': frozenset({'barrens', 'dustwallow_marsh', 'thousand_needles'}),
    'razorfen_kraul': frozenset({'barrens', 'dustwallow_marsh', 'thousand_needles'}),
    'ruby_sanctum': frozenset({'dragonblight'}),
    'ruins_of_ahn_qiraj': frozenset(),
    'scarlet_monastery': frozenset({'tirisfal_glades', 'western_plaguelands'}),
    'scholomance': frozenset({'eastern_plaguelands', 'hinterlands', 'western_plaguelands'}),
    'shadowfang_keep': frozenset({'silverpine_forest'}),
    'stormwind_stockade': frozenset({'elwynn_forest', 'stormwind_city'}),
    'stratholme': frozenset({'eastern_plaguelands'}),
    'sunken_temple': frozenset({'swamp_of_sorrows'}),
    'sunwell': frozenset({'isle_of_quel_danas'}),
    'tempest_keep': frozenset({'netherstorm'}),
    'tempest_keep_the_arcatraz': frozenset({'netherstorm'}),
    'tempest_keep_the_botanica': frozenset({'netherstorm'}),
    'tempest_keep_the_mechanar': frozenset({'netherstorm'}),
    'trial_of_the_champion': frozenset({'hrothgar_s_landing', 'icecrown', 'storm_peaks'}),
    'trial_of_the_crusader': frozenset({'hrothgar_s_landing', 'icecrown', 'storm_peaks'}),
    'uldaman': frozenset({'badlands', 'dun_morogh', 'loch_modan'}),
    'ulduar': frozenset({'storm_peaks'}),
    'utgarde_keep': frozenset({'howling_fjord'}),
    'utgarde_pinnacle': frozenset({'howling_fjord'}),
    'vault_of_archavon': frozenset({'dragonblight', 'icecrown', 'sholazar_basin', 'wintergrasp'}),
    'violet_hold': frozenset({'crystalsong_forest', 'icecrown', 'storm_peaks'}),
    'wailing_caverns': frozenset({'barrens', 'durotar', 'mulgore'}),
    'zul_aman': frozenset({'ghostlands'}),
    'zul_farrak': frozenset({'tanaris', 'thousand_needles', 'un_goro_crater'}),
    'zul_gurub': frozenset({'stranglethorn_vale'}),
}
