# GENERATED FILE - do not edit by hand.
# Regenerate with: python modules/archipelago_wow/tools/generate_content.py content/rares.yaml


LOCATIONS: dict[str, int] = {
    "Rare Kill: Lost Soul": 730000,
    "Rare Kill: Snagglespear": 730001,
    "Rare Kill: Morgaine the Sly": 730002,
    "Rare Kill: Sister Hatelash": 730003,
    "Rare Kill: Bjarn": 730004,
    "Rare Kill: Grizlak": 730005,
    "Rare Kill: Carnivous the Breaker": 730006,
    "Rare Kill: Dr. Whitherlimb": 730007,
    "Rare Kill: Engineer Whirleygig": 730008,
    "Rare Kill: Magosh": 730009,
    "Rare Kill: Taskmaster Whipfang": 730010,
    "Rare Kill: Chatter": 730011,
    "Rare Kill: Leech Widow": 730012,
    "Rare Kill: Branch Snapper": 730013,
    "Rare Kill: Kazon": 730014,
    "Rare Kill: Brother Ravenoak": 730015,
    "Rare Kill: Commander Felstrom": 730016,
    "Rare Kill: Giggler": 730017,
    "Rare Kill: Kovork": 730018,
    "Rare Kill: Drogoth the Roamer": 730019,
    "Rare Kill: Hayoc": 730020,
    "Rare Kill: Brimgore": 730021,
    "Rare Kill: Gilmorian": 730022,
    "Rare Kill: Rumbler": 730023,
    "Rare Kill: Faulty War Golem": 730024,
    "Rare Kill: Antilus the Soarer": 730025,
    "Rare Kill: Jalinde Summerdrake": 730026,
    "Rare Kill: Antilos": 730027,
    "Rare Kill: Lady Sesspira": 730028,
    "Rare Kill: Olm the Wise": 730029,
    "Rare Kill: Mezzir the Howler": 730030,
    "Rare Kill: Gish the Unmoving": 730031,
    "Rare Kill: Grubthor": 730032,
    "Rare Kill: High General Abbendis": 730033,
    "Rare Kill: Scarlet Executioner": 730034,
    "Rare Kill: Foreman Jerris": 730035,
    "Rare Kill: Goretooth": 730036,
    "Rare Kill: Ambassador Jerrikar": 730037,
    "Rare Kill: Tukemuth": 730038,
    "Rare Kill: Gondria": 730039,
}

ITEMS: dict[str, tuple[int, int]] = {
    "Key Hunt: Key": (730040, 40),
}

TAGS: dict[str, dict[str, frozenset[str]]] = {
    "Rare Kill: Lost Soul": {"area": frozenset({"tirisfal_glades"})},
    "Rare Kill: Snagglespear": {"area": frozenset({"barrens", "feralas", "mulgore"})},
    "Rare Kill: Morgaine the Sly": {"area": frozenset({"elwynn_forest", "westfall"})},
    "Rare Kill: Sister Hatelash": {"area": frozenset({"barrens", "desolace", "mulgore"})},
    "Rare Kill: Bjarn": {"area": frozenset({"dun_morogh"})},
    "Rare Kill: Grizlak": {"area": frozenset({"dun_morogh", "loch_modan"})},
    "Rare Kill: Carnivous the Breaker": {"area": frozenset({"darkshore", "felwood"})},
    "Rare Kill: Dr. Whitherlimb": {"area": frozenset({"ghostlands"})},
    "Rare Kill: Engineer Whirleygig": {"area": frozenset({"ashenvale", "barrens", "durotar"})},
    "Rare Kill: Magosh": {"area": frozenset({"loch_modan"})},
    "Rare Kill: Taskmaster Whipfang": {"area": frozenset({"ashenvale", "barrens", "stonetalon_mountains"})},
    "Rare Kill: Chatter": {"area": frozenset({"redridge_mountains"})},
    "Rare Kill: Leech Widow": {"area": frozenset({"wetlands"})},
    "Rare Kill: Branch Snapper": {"area": frozenset({"ashenvale"})},
    "Rare Kill: Kazon": {"area": frozenset({"burning_steppes", "redridge_mountains"})},
    "Rare Kill: Brother Ravenoak": {"area": frozenset({"stonetalon_mountains"})},
    "Rare Kill: Commander Felstrom": {"area": frozenset({"duskwood", "westfall"})},
    "Rare Kill: Giggler": {"area": frozenset({"barrens", "desolace", "mulgore"})},
    "Rare Kill: Kovork": {"area": frozenset({"arathi_highlands", "hillsbrad_foothills"})},
    "Rare Kill: Drogoth the Roamer": {"area": frozenset({"barrens", "dustwallow_marsh", "mulgore"})},
    "Rare Kill: Hayoc": {"area": frozenset({"barrens", "dustwallow_marsh", "thousand_needles"})},
    "Rare Kill: Brimgore": {"area": frozenset({"barrens", "dustwallow_marsh", "thousand_needles"})},
    "Rare Kill: Gilmorian": {"area": frozenset({"blasted_lands", "swamp_of_sorrows"})},
    "Rare Kill: Rumbler": {"area": frozenset({"badlands", "burning_steppes", "searing_gorge"})},
    "Rare Kill: Faulty War Golem": {"area": frozenset({"burning_steppes", "dun_morogh", "searing_gorge"})},
    "Rare Kill: Antilus the Soarer": {"area": frozenset({"feralas"})},
    "Rare Kill: Jalinde Summerdrake": {"area": frozenset({"hinterlands"})},
    "Rare Kill: Antilos": {"area": frozenset({"azshara"})},
    "Rare Kill: Lady Sesspira": {"area": frozenset({"azshara"})},
    "Rare Kill: Olm the Wise": {"area": frozenset({"darkshore", "felwood", "winterspring"})},
    "Rare Kill: Mezzir the Howler": {"area": frozenset({"darkshore", "felwood", "winterspring"})},
    "Rare Kill: Gish the Unmoving": {"area": frozenset({"eastern_plaguelands"})},
    "Rare Kill: Grubthor": {"area": frozenset({"silithus"})},
    "Rare Kill: High General Abbendis": {"area": frozenset({"eastern_plaguelands"})},
    "Rare Kill: Scarlet Executioner": {"area": frozenset({"western_plaguelands"})},
    "Rare Kill: Foreman Jerris": {"area": frozenset({"western_plaguelands"})},
    "Rare Kill: Goretooth": {"area": frozenset({"nagrand", "terokkar_forest", "zangarmarsh"})},
    "Rare Kill: Ambassador Jerrikar": {"area": frozenset({"shadowmoon_valley", "terokkar_forest"})},
    "Rare Kill: Tukemuth": {"area": frozenset({"dragonblight"})},
    "Rare Kill: Gondria": {"area": frozenset({"grizzly_hills", "storm_peaks", "zul_drak"})},
}
