# GENERATED FILE - do not edit by hand.
# Regenerate with: python modules/archipelago_wow/tools/generate_content.py content/rares.yaml


LOCATIONS: dict[str, int] = {
    "Rare Kill: Lost Soul": 730000,
    "Rare Kill: Snagglespear": 730001,
    "Rare Kill: Morgaine the Sly": 730002,
    "Rare Kill: Sister Hatelash": 730003,
    "Rare Kill: Bjarn": 730004,
    "Rare Kill: Grizlak": 730005,
    "Rare Kill: Carnivous the Breaker": 730006,
    "Rare Kill: Dr. Whitherlimb": 730007,
    "Rare Kill: Engineer Whirleygig": 730008,
    "Rare Kill: Magosh": 730009,
    "Rare Kill: Taskmaster Whipfang": 730010,
    "Rare Kill: Chatter": 730011,
    "Rare Kill: Leech Widow": 730012,
    "Rare Kill: Branch Snapper": 730013,
    "Rare Kill: Kazon": 730014,
    "Rare Kill: Brother Ravenoak": 730015,
    "Rare Kill: Commander Felstrom": 730016,
    "Rare Kill: Giggler": 730017,
    "Rare Kill: Kovork": 730018,
    "Rare Kill: Drogoth the Roamer": 730019,
    "Rare Kill: Hayoc": 730020,
    "Rare Kill: Brimgore": 730021,
    "Rare Kill: Gilmorian": 730022,
    "Rare Kill: Rumbler": 730023,
    "Rare Kill: Faulty War Golem": 730024,
    "Rare Kill: Antilus the Soarer": 730025,
    "Rare Kill: Jalinde Summerdrake": 730026,
    "Rare Kill: Antilos": 730027,
    "Rare Kill: Lady Sesspira": 730028,
    "Rare Kill: Olm the Wise": 730029,
    "Rare Kill: Mezzir the Howler": 730030,
    "Rare Kill: Gish the Unmoving": 730031,
    "Rare Kill: Grubthor": 730032,
    "Rare Kill: High General Abbendis": 730033,
    "Rare Kill: Scarlet Executioner": 730034,
    "Rare Kill: Foreman Jerris": 730035,
    "Rare Kill: Goretooth": 730036,
    "Rare Kill: Ambassador Jerrikar": 730037,
    "Rare Kill: Tukemuth": 730038,
    "Rare Kill: Gondria": 730039,
}

ITEMS: dict[str, tuple[int, int]] = {
    "Key Hunt: Key": (730040, 40),
}

TAGS: dict[str, dict[str, frozenset[str]]] = {
    "Rare Kill: Lost Soul": {"zone": frozenset({"tirisfal_glades"})},
    "Rare Kill: Snagglespear": {"zone": frozenset({"mulgore"})},
    "Rare Kill: Morgaine the Sly": {"zone": frozenset({"elwynn_forest"})},
    "Rare Kill: Sister Hatelash": {"zone": frozenset({"desolace"})},
    "Rare Kill: Bjarn": {"zone": frozenset({"dun_morogh"})},
    "Rare Kill: Grizlak": {"zone": frozenset({"loch_modan"})},
    "Rare Kill: Carnivous the Breaker": {"zone": frozenset({"felwood"})},
    "Rare Kill: Dr. Whitherlimb": {"zone": frozenset({"ghostlands"})},
    "Rare Kill: Engineer Whirleygig": {"zone": frozenset({"durotar"})},
    "Rare Kill: Magosh": {"zone": frozenset({"loch_modan"})},
    "Rare Kill: Taskmaster Whipfang": {"zone": frozenset({"stonetalon_mountains"})},
    "Rare Kill: Chatter": {"zone": frozenset({"redridge_mountains"})},
    "Rare Kill: Leech Widow": {"zone": frozenset({"wetlands"})},
    "Rare Kill: Branch Snapper": {"zone": frozenset({"ashenvale"})},
    "Rare Kill: Kazon": {"zone": frozenset({"redridge_mountains"})},
    "Rare Kill: Brother Ravenoak": {"zone": frozenset({"stonetalon_mountains"})},
    "Rare Kill: Commander Felstrom": {"zone": frozenset({"duskwood"})},
    "Rare Kill: Giggler": {"zone": frozenset({"desolace"})},
    "Rare Kill: Kovork": {"zone": frozenset({"hillsbrad_foothills"})},
    "Rare Kill: Drogoth the Roamer": {"zone": frozenset({"dustwallow_marsh"})},
    "Rare Kill: Hayoc": {"zone": frozenset({"thousand_needles"})},
    "Rare Kill: Brimgore": {"zone": frozenset({"thousand_needles"})},
    "Rare Kill: Gilmorian": {"zone": frozenset({"swamp_of_sorrows"})},
    "Rare Kill: Rumbler": {"zone": frozenset({"searing_gorge"})},
    "Rare Kill: Faulty War Golem": {"zone": frozenset({"searing_gorge"})},
    "Rare Kill: Antilus the Soarer": {"zone": frozenset({"feralas"})},
    "Rare Kill: Jalinde Summerdrake": {"zone": frozenset({"the_hinterlands"})},
    "Rare Kill: Antilos": {"zone": frozenset({"azshara"})},
    "Rare Kill: Lady Sesspira": {"zone": frozenset({"azshara"})},
    "Rare Kill: Olm the Wise": {"zone": frozenset({"felwood"})},
    "Rare Kill: Mezzir the Howler": {"zone": frozenset({"felwood"})},
    "Rare Kill: Gish the Unmoving": {"zone": frozenset({"eastern_plaguelands"})},
    "Rare Kill: Grubthor": {"zone": frozenset({"silithus"})},
    "Rare Kill: High General Abbendis": {"zone": frozenset({"eastern_plaguelands"})},
    "Rare Kill: Scarlet Executioner": {"zone": frozenset({"western_plaguelands"})},
    "Rare Kill: Foreman Jerris": {"zone": frozenset({"western_plaguelands"})},
    "Rare Kill: Goretooth": {"zone": frozenset({"nagrand"})},
    "Rare Kill: Ambassador Jerrikar": {"zone": frozenset({"shadowmoon_valley"})},
    "Rare Kill: Tukemuth": {"zone": frozenset({"dragonblight"})},
    "Rare Kill: Gondria": {"zone": frozenset({"zul_drak"})},
}
