# GENERATED FILE - do not edit by hand.
# Regenerate with: python modules/archipelago_wow/tools/generate_content.py content/repsanity.yaml


LOCATIONS: dict[str, int] = {
    "Reputation: Booty Bay (Friendly)": 11000000,
    "Reputation: Booty Bay (Honored)": 11000001,
    "Reputation: Booty Bay (Revered)": 11000002,
    "Reputation: Booty Bay (Exalted)": 11000003,
    "Reputation: Ironforge (Friendly)": 11000004,
    "Reputation: Ironforge (Honored)": 11000005,
    "Reputation: Ironforge (Revered)": 11000006,
    "Reputation: Ironforge (Exalted)": 11000007,
    "Reputation: Gnomeregan Exiles (Friendly)": 11000008,
    "Reputation: Gnomeregan Exiles (Honored)": 11000009,
    "Reputation: Gnomeregan Exiles (Revered)": 11000010,
    "Reputation: Gnomeregan Exiles (Exalted)": 11000011,
    "Reputation: Thorium Brotherhood (Friendly)": 11000012,
    "Reputation: Thorium Brotherhood (Honored)": 11000013,
    "Reputation: Thorium Brotherhood (Revered)": 11000014,
    "Reputation: Thorium Brotherhood (Exalted)": 11000015,
    "Reputation: Undercity (Friendly)": 11000016,
    "Reputation: Undercity (Honored)": 11000017,
    "Reputation: Undercity (Revered)": 11000018,
    "Reputation: Undercity (Exalted)": 11000019,
    "Reputation: Darnassus (Friendly)": 11000020,
    "Reputation: Darnassus (Honored)": 11000021,
    "Reputation: Darnassus (Revered)": 11000022,
    "Reputation: Darnassus (Exalted)": 11000023,
    "Reputation: Syndicate (Hostile)": 11000024,
    "Reputation: Syndicate (Unfriendly)": 11000025,
    "Reputation: Syndicate (Neutral)": 11000026,
    "Reputation: Syndicate (Friendly)": 11000027,
    "Reputation: Syndicate (Honored)": 11000028,
    "Reputation: Syndicate (Revered)": 11000029,
    "Reputation: Syndicate (Exalted)": 11000030,
    "Reputation: Stormwind (Friendly)": 11000031,
    "Reputation: Stormwind (Honored)": 11000032,
    "Reputation: Stormwind (Revered)": 11000033,
    "Reputation: Stormwind (Exalted)": 11000034,
    "Reputation: Orgrimmar (Friendly)": 11000035,
    "Reputation: Orgrimmar (Honored)": 11000036,
    "Reputation: Orgrimmar (Revered)": 11000037,
    "Reputation: Orgrimmar (Exalted)": 11000038,
    "Reputation: Thunder Bluff (Friendly)": 11000039,
    "Reputation: Thunder Bluff (Honored)": 11000040,
    "Reputation: Thunder Bluff (Revered)": 11000041,
    "Reputation: Thunder Bluff (Exalted)": 11000042,
    "Reputation: Bloodsail Buccaneers (Hostile)": 11000043,
    "Reputation: Bloodsail Buccaneers (Unfriendly)": 11000044,
    "Reputation: Bloodsail Buccaneers (Neutral)": 11000045,
    "Reputation: Bloodsail Buccaneers (Friendly)": 11000046,
    "Reputation: Bloodsail Buccaneers (Honored)": 11000047,
    "Reputation: Bloodsail Buccaneers (Revered)": 11000048,
    "Reputation: Bloodsail Buccaneers (Exalted)": 11000049,
    "Reputation: Gelkis Clan Centaur (Friendly)": 11000050,
    "Reputation: Gelkis Clan Centaur (Honored)": 11000051,
    "Reputation: Gelkis Clan Centaur (Revered)": 11000052,
    "Reputation: Gelkis Clan Centaur (Exalted)": 11000053,
    "Reputation: Magram Clan Centaur (Friendly)": 11000054,
    "Reputation: Magram Clan Centaur (Honored)": 11000055,
    "Reputation: Magram Clan Centaur (Revered)": 11000056,
    "Reputation: Magram Clan Centaur (Exalted)": 11000057,
    "Reputation: Steamwheedle Cartel (Friendly)": 11000058,
    "Reputation: Steamwheedle Cartel (Honored)": 11000059,
    "Reputation: Steamwheedle Cartel (Revered)": 11000060,
    "Reputation: Steamwheedle Cartel (Exalted)": 11000061,
    "Reputation: Zandalar Tribe (Friendly)": 11000062,
    "Reputation: Zandalar Tribe (Honored)": 11000063,
    "Reputation: Zandalar Tribe (Revered)": 11000064,
    "Reputation: Zandalar Tribe (Exalted)": 11000065,
    "Reputation: Ravenholdt (Friendly)": 11000066,
    "Reputation: Ravenholdt (Honored)": 11000067,
    "Reputation: Ravenholdt (Revered)": 11000068,
    "Reputation: Ravenholdt (Exalted)": 11000069,
    "Reputation: Gadgetzan (Friendly)": 11000070,
    "Reputation: Gadgetzan (Honored)": 11000071,
    "Reputation: Gadgetzan (Revered)": 11000072,
    "Reputation: Gadgetzan (Exalted)": 11000073,
    "Reputation: Ratchet (Friendly)": 11000074,
    "Reputation: Ratchet (Honored)": 11000075,
    "Reputation: Ratchet (Revered)": 11000076,
    "Reputation: Ratchet (Exalted)": 11000077,
    "Reputation: Wildhammer Clan (Friendly)": 11000078,
    "Reputation: Wildhammer Clan (Honored)": 11000079,
    "Reputation: Wildhammer Clan (Revered)": 11000080,
    "Reputation: Wildhammer Clan (Exalted)": 11000081,
    "Reputation: The League of Arathor (Friendly)": 11000082,
    "Reputation: The League of Arathor (Honored)": 11000083,
    "Reputation: The League of Arathor (Revered)": 11000084,
    "Reputation: The League of Arathor (Exalted)": 11000085,
    "Reputation: The Defilers (Friendly)": 11000086,
    "Reputation: The Defilers (Honored)": 11000087,
    "Reputation: The Defilers (Revered)": 11000088,
    "Reputation: The Defilers (Exalted)": 11000089,
    "Reputation: Argent Dawn (Friendly)": 11000090,
    "Reputation: Argent Dawn (Honored)": 11000091,
    "Reputation: Argent Dawn (Revered)": 11000092,
    "Reputation: Argent Dawn (Exalted)": 11000093,
    "Reputation: Darkspear Trolls (Friendly)": 11000094,
    "Reputation: Darkspear Trolls (Honored)": 11000095,
    "Reputation: Darkspear Trolls (Revered)": 11000096,
    "Reputation: Darkspear Trolls (Exalted)": 11000097,
    "Reputation: Caer Darrow (Friendly)": 11000098,
    "Reputation: Caer Darrow (Honored)": 11000099,
    "Reputation: Caer Darrow (Revered)": 11000100,
    "Reputation: Caer Darrow (Exalted)": 11000101,
    "Reputation: Timbermaw Hold (Unfriendly)": 11000102,
    "Reputation: Timbermaw Hold (Neutral)": 11000103,
    "Reputation: Timbermaw Hold (Friendly)": 11000104,
    "Reputation: Timbermaw Hold (Honored)": 11000105,
    "Reputation: Timbermaw Hold (Revered)": 11000106,
    "Reputation: Timbermaw Hold (Exalted)": 11000107,
    "Reputation: Everlook (Friendly)": 11000108,
    "Reputation: Everlook (Honored)": 11000109,
    "Reputation: Everlook (Revered)": 11000110,
    "Reputation: Everlook (Exalted)": 11000111,
    "Reputation: Wintersaber Trainers (Hostile)": 11000112,
    "Reputation: Wintersaber Trainers (Unfriendly)": 11000113,
    "Reputation: Wintersaber Trainers (Neutral)": 11000114,
    "Reputation: Wintersaber Trainers (Friendly)": 11000115,
    "Reputation: Wintersaber Trainers (Honored)": 11000116,
    "Reputation: Wintersaber Trainers (Revered)": 11000117,
    "Reputation: Wintersaber Trainers (Exalted)": 11000118,
    "Reputation: Cenarion Circle (Friendly)": 11000119,
    "Reputation: Cenarion Circle (Honored)": 11000120,
    "Reputation: Cenarion Circle (Revered)": 11000121,
    "Reputation: Cenarion Circle (Exalted)": 11000122,
    "Reputation: Frostwolf Clan (Friendly)": 11000123,
    "Reputation: Frostwolf Clan (Honored)": 11000124,
    "Reputation: Frostwolf Clan (Revered)": 11000125,
    "Reputation: Frostwolf Clan (Exalted)": 11000126,
    "Reputation: Stormpike Guard (Friendly)": 11000127,
    "Reputation: Stormpike Guard (Honored)": 11000128,
    "Reputation: Stormpike Guard (Revered)": 11000129,
    "Reputation: Stormpike Guard (Exalted)": 11000130,
    "Reputation: Hydraxian Waterlords (Friendly)": 11000131,
    "Reputation: Hydraxian Waterlords (Honored)": 11000132,
    "Reputation: Hydraxian Waterlords (Revered)": 11000133,
    "Reputation: Hydraxian Waterlords (Exalted)": 11000134,
    "Reputation: Shen'dralar (Friendly)": 11000135,
    "Reputation: Shen'dralar (Honored)": 11000136,
    "Reputation: Shen'dralar (Revered)": 11000137,
    "Reputation: Shen'dralar (Exalted)": 11000138,
    "Reputation: Warsong Outriders (Friendly)": 11000139,
    "Reputation: Warsong Outriders (Honored)": 11000140,
    "Reputation: Warsong Outriders (Revered)": 11000141,
    "Reputation: Warsong Outriders (Exalted)": 11000142,
    "Reputation: Silverwing Sentinels (Friendly)": 11000143,
    "Reputation: Silverwing Sentinels (Honored)": 11000144,
    "Reputation: Silverwing Sentinels (Revered)": 11000145,
    "Reputation: Silverwing Sentinels (Exalted)": 11000146,
    "Reputation: Darkmoon Faire (Friendly)": 11000147,
    "Reputation: Darkmoon Faire (Honored)": 11000148,
    "Reputation: Darkmoon Faire (Revered)": 11000149,
    "Reputation: Darkmoon Faire (Exalted)": 11000150,
    "Reputation: Brood of Nozdormu (Hostile)": 11000151,
    "Reputation: Brood of Nozdormu (Unfriendly)": 11000152,
    "Reputation: Brood of Nozdormu (Neutral)": 11000153,
    "Reputation: Brood of Nozdormu (Friendly)": 11000154,
    "Reputation: Brood of Nozdormu (Honored)": 11000155,
    "Reputation: Brood of Nozdormu (Revered)": 11000156,
    "Reputation: Brood of Nozdormu (Exalted)": 11000157,
    "Reputation: Silvermoon City (Friendly)": 11000158,
    "Reputation: Silvermoon City (Honored)": 11000159,
    "Reputation: Silvermoon City (Revered)": 11000160,
    "Reputation: Silvermoon City (Exalted)": 11000161,
    "Reputation: Tranquillien (Friendly)": 11000162,
    "Reputation: Tranquillien (Honored)": 11000163,
    "Reputation: Tranquillien (Revered)": 11000164,
    "Reputation: Tranquillien (Exalted)": 11000165,
    "Reputation: Exodar (Friendly)": 11000166,
    "Reputation: Exodar (Honored)": 11000167,
    "Reputation: Exodar (Revered)": 11000168,
    "Reputation: Exodar (Exalted)": 11000169,
    "Reputation: The Aldor (Unfriendly)": 11000170,
    "Reputation: The Aldor (Neutral)": 11000171,
    "Reputation: The Aldor (Friendly)": 11000172,
    "Reputation: The Aldor (Honored)": 11000173,
    "Reputation: The Aldor (Revered)": 11000174,
    "Reputation: The Aldor (Exalted)": 11000175,
    "Reputation: The Consortium (Friendly)": 11000176,
    "Reputation: The Consortium (Honored)": 11000177,
    "Reputation: The Consortium (Revered)": 11000178,
    "Reputation: The Consortium (Exalted)": 11000179,
    "Reputation: The Scryers (Unfriendly)": 11000180,
    "Reputation: The Scryers (Neutral)": 11000181,
    "Reputation: The Scryers (Friendly)": 11000182,
    "Reputation: The Scryers (Honored)": 11000183,
    "Reputation: The Scryers (Revered)": 11000184,
    "Reputation: The Scryers (Exalted)": 11000185,
    "Reputation: The Sha'tar (Friendly)": 11000186,
    "Reputation: The Sha'tar (Honored)": 11000187,
    "Reputation: The Sha'tar (Revered)": 11000188,
    "Reputation: The Sha'tar (Exalted)": 11000189,
    "Reputation: Shattrath City (Friendly)": 11000190,
    "Reputation: Shattrath City (Honored)": 11000191,
    "Reputation: Shattrath City (Revered)": 11000192,
    "Reputation: Shattrath City (Exalted)": 11000193,
    "Reputation: The Mag'har (Neutral)": 11000194,
    "Reputation: The Mag'har (Friendly)": 11000195,
    "Reputation: The Mag'har (Honored)": 11000196,
    "Reputation: The Mag'har (Revered)": 11000197,
    "Reputation: The Mag'har (Exalted)": 11000198,
    "Reputation: Cenarion Expedition (Friendly)": 11000199,
    "Reputation: Cenarion Expedition (Honored)": 11000200,
    "Reputation: Cenarion Expedition (Revered)": 11000201,
    "Reputation: Cenarion Expedition (Exalted)": 11000202,
    "Reputation: Honor Hold (Friendly)": 11000203,
    "Reputation: Honor Hold (Honored)": 11000204,
    "Reputation: Honor Hold (Revered)": 11000205,
    "Reputation: Honor Hold (Exalted)": 11000206,
    "Reputation: Thrallmar (Friendly)": 11000207,
    "Reputation: Thrallmar (Honored)": 11000208,
    "Reputation: Thrallmar (Revered)": 11000209,
    "Reputation: Thrallmar (Exalted)": 11000210,
    "Reputation: The Violet Eye (Friendly)": 11000211,
    "Reputation: The Violet Eye (Honored)": 11000212,
    "Reputation: The Violet Eye (Revered)": 11000213,
    "Reputation: The Violet Eye (Exalted)": 11000214,
    "Reputation: Sporeggar (Neutral)": 11000215,
    "Reputation: Sporeggar (Friendly)": 11000216,
    "Reputation: Sporeggar (Honored)": 11000217,
    "Reputation: Sporeggar (Revered)": 11000218,
    "Reputation: Sporeggar (Exalted)": 11000219,
    "Reputation: Kurenai (Neutral)": 11000220,
    "Reputation: Kurenai (Friendly)": 11000221,
    "Reputation: Kurenai (Honored)": 11000222,
    "Reputation: Kurenai (Revered)": 11000223,
    "Reputation: Kurenai (Exalted)": 11000224,
    "Reputation: Keepers of Time (Friendly)": 11000225,
    "Reputation: Keepers of Time (Honored)": 11000226,
    "Reputation: Keepers of Time (Revered)": 11000227,
    "Reputation: Keepers of Time (Exalted)": 11000228,
    "Reputation: The Scale of the Sands (Friendly)": 11000229,
    "Reputation: The Scale of the Sands (Honored)": 11000230,
    "Reputation: The Scale of the Sands (Revered)": 11000231,
    "Reputation: The Scale of the Sands (Exalted)": 11000232,
    "Reputation: Lower City (Friendly)": 11000233,
    "Reputation: Lower City (Honored)": 11000234,
    "Reputation: Lower City (Revered)": 11000235,
    "Reputation: Lower City (Exalted)": 11000236,
    "Reputation: Ashtongue Deathsworn (Friendly)": 11000237,
    "Reputation: Ashtongue Deathsworn (Honored)": 11000238,
    "Reputation: Ashtongue Deathsworn (Revered)": 11000239,
    "Reputation: Ashtongue Deathsworn (Exalted)": 11000240,
    "Reputation: Netherwing (Hostile)": 11000241,
    "Reputation: Netherwing (Unfriendly)": 11000242,
    "Reputation: Netherwing (Neutral)": 11000243,
    "Reputation: Netherwing (Friendly)": 11000244,
    "Reputation: Netherwing (Honored)": 11000245,
    "Reputation: Netherwing (Revered)": 11000246,
    "Reputation: Netherwing (Exalted)": 11000247,
    "Reputation: Sha'tari Skyguard (Friendly)": 11000248,
    "Reputation: Sha'tari Skyguard (Honored)": 11000249,
    "Reputation: Sha'tari Skyguard (Revered)": 11000250,
    "Reputation: Sha'tari Skyguard (Exalted)": 11000251,
    "Reputation: Alliance Vanguard (Friendly)": 11000252,
    "Reputation: Alliance Vanguard (Honored)": 11000253,
    "Reputation: Alliance Vanguard (Revered)": 11000254,
    "Reputation: Alliance Vanguard (Exalted)": 11000255,
    "Reputation: Ogri'la (Friendly)": 11000256,
    "Reputation: Ogri'la (Honored)": 11000257,
    "Reputation: Ogri'la (Revered)": 11000258,
    "Reputation: Ogri'la (Exalted)": 11000259,
    "Reputation: Valiance Expedition (Friendly)": 11000260,
    "Reputation: Valiance Expedition (Honored)": 11000261,
    "Reputation: Valiance Expedition (Revered)": 11000262,
    "Reputation: Valiance Expedition (Exalted)": 11000263,
    "Reputation: Horde Expedition (Friendly)": 11000264,
    "Reputation: Horde Expedition (Honored)": 11000265,
    "Reputation: Horde Expedition (Revered)": 11000266,
    "Reputation: Horde Expedition (Exalted)": 11000267,
    "Reputation: The Taunka (Friendly)": 11000268,
    "Reputation: The Taunka (Honored)": 11000269,
    "Reputation: The Taunka (Revered)": 11000270,
    "Reputation: The Taunka (Exalted)": 11000271,
    "Reputation: The Hand of Vengeance (Friendly)": 11000272,
    "Reputation: The Hand of Vengeance (Honored)": 11000273,
    "Reputation: The Hand of Vengeance (Revered)": 11000274,
    "Reputation: The Hand of Vengeance (Exalted)": 11000275,
    "Reputation: Explorers' League (Friendly)": 11000276,
    "Reputation: Explorers' League (Honored)": 11000277,
    "Reputation: Explorers' League (Revered)": 11000278,
    "Reputation: Explorers' League (Exalted)": 11000279,
    "Reputation: The Kalu'ak (Friendly)": 11000280,
    "Reputation: The Kalu'ak (Honored)": 11000281,
    "Reputation: The Kalu'ak (Revered)": 11000282,
    "Reputation: The Kalu'ak (Exalted)": 11000283,
    "Reputation: Shattered Sun Offensive (Friendly)": 11000284,
    "Reputation: Shattered Sun Offensive (Honored)": 11000285,
    "Reputation: Shattered Sun Offensive (Revered)": 11000286,
    "Reputation: Shattered Sun Offensive (Exalted)": 11000287,
    "Reputation: Warsong Offensive (Friendly)": 11000288,
    "Reputation: Warsong Offensive (Honored)": 11000289,
    "Reputation: Warsong Offensive (Revered)": 11000290,
    "Reputation: Warsong Offensive (Exalted)": 11000291,
    "Reputation: Kirin Tor (Friendly)": 11000292,
    "Reputation: Kirin Tor (Honored)": 11000293,
    "Reputation: Kirin Tor (Revered)": 11000294,
    "Reputation: Kirin Tor (Exalted)": 11000295,
    "Reputation: The Wyrmrest Accord (Friendly)": 11000296,
    "Reputation: The Wyrmrest Accord (Honored)": 11000297,
    "Reputation: The Wyrmrest Accord (Revered)": 11000298,
    "Reputation: The Wyrmrest Accord (Exalted)": 11000299,
    "Reputation: The Silver Covenant (Friendly)": 11000300,
    "Reputation: The Silver Covenant (Honored)": 11000301,
    "Reputation: The Silver Covenant (Revered)": 11000302,
    "Reputation: The Silver Covenant (Exalted)": 11000303,
    "Reputation: Knights of the Ebon Blade (Friendly)": 11000304,
    "Reputation: Knights of the Ebon Blade (Honored)": 11000305,
    "Reputation: Knights of the Ebon Blade (Revered)": 11000306,
    "Reputation: Knights of the Ebon Blade (Exalted)": 11000307,
    "Reputation: Frenzyheart Tribe (Friendly)": 11000308,
    "Reputation: Frenzyheart Tribe (Honored)": 11000309,
    "Reputation: Frenzyheart Tribe (Revered)": 11000310,
    "Reputation: Frenzyheart Tribe (Exalted)": 11000311,
    "Reputation: The Oracles (Friendly)": 11000312,
    "Reputation: The Oracles (Honored)": 11000313,
    "Reputation: The Oracles (Revered)": 11000314,
    "Reputation: The Oracles (Exalted)": 11000315,
    "Reputation: Argent Crusade (Friendly)": 11000316,
    "Reputation: Argent Crusade (Honored)": 11000317,
    "Reputation: Argent Crusade (Revered)": 11000318,
    "Reputation: Argent Crusade (Exalted)": 11000319,
    "Reputation: The Sons of Hodir (Hostile)": 11000320,
    "Reputation: The Sons of Hodir (Unfriendly)": 11000321,
    "Reputation: The Sons of Hodir (Neutral)": 11000322,
    "Reputation: The Sons of Hodir (Friendly)": 11000323,
    "Reputation: The Sons of Hodir (Honored)": 11000324,
    "Reputation: The Sons of Hodir (Revered)": 11000325,
    "Reputation: The Sons of Hodir (Exalted)": 11000326,
    "Reputation: The Sunreavers (Friendly)": 11000327,
    "Reputation: The Sunreavers (Honored)": 11000328,
    "Reputation: The Sunreavers (Revered)": 11000329,
    "Reputation: The Sunreavers (Exalted)": 11000330,
    "Reputation: The Frostborn (Friendly)": 11000331,
    "Reputation: The Frostborn (Honored)": 11000332,
    "Reputation: The Frostborn (Revered)": 11000333,
    "Reputation: The Frostborn (Exalted)": 11000334,
    "Reputation: The Ashen Verdict (Friendly)": 11000335,
    "Reputation: The Ashen Verdict (Honored)": 11000336,
    "Reputation: The Ashen Verdict (Revered)": 11000337,
    "Reputation: The Ashen Verdict (Exalted)": 11000338,
}

ITEMS: dict[str, tuple[int, int]] = {
}

ALWAYS_PRESENT: frozenset[str] = frozenset({
})

TRIGGERS: dict[str, dict] = {
    "Reputation: Booty Bay (Friendly)": {'kind': 'reputation_rank', 'faction_id': 21, 'rank': 4},
    "Reputation: Booty Bay (Honored)": {'kind': 'reputation_rank', 'faction_id': 21, 'rank': 5},
    "Reputation: Booty Bay (Revered)": {'kind': 'reputation_rank', 'faction_id': 21, 'rank': 6},
    "Reputation: Booty Bay (Exalted)": {'kind': 'reputation_rank', 'faction_id': 21, 'rank': 7},
    "Reputation: Ironforge (Friendly)": {'kind': 'reputation_rank', 'faction_id': 47, 'rank': 4},
    "Reputation: Ironforge (Honored)": {'kind': 'reputation_rank', 'faction_id': 47, 'rank': 5},
    "Reputation: Ironforge (Revered)": {'kind': 'reputation_rank', 'faction_id': 47, 'rank': 6},
    "Reputation: Ironforge (Exalted)": {'kind': 'reputation_rank', 'faction_id': 47, 'rank': 7},
    "Reputation: Gnomeregan Exiles (Friendly)": {'kind': 'reputation_rank', 'faction_id': 54, 'rank': 4},
    "Reputation: Gnomeregan Exiles (Honored)": {'kind': 'reputation_rank', 'faction_id': 54, 'rank': 5},
    "Reputation: Gnomeregan Exiles (Revered)": {'kind': 'reputation_rank', 'faction_id': 54, 'rank': 6},
    "Reputation: Gnomeregan Exiles (Exalted)": {'kind': 'reputation_rank', 'faction_id': 54, 'rank': 7},
    "Reputation: Thorium Brotherhood (Friendly)": {'kind': 'reputation_rank', 'faction_id': 59, 'rank': 4},
    "Reputation: Thorium Brotherhood (Honored)": {'kind': 'reputation_rank', 'faction_id': 59, 'rank': 5},
    "Reputation: Thorium Brotherhood (Revered)": {'kind': 'reputation_rank', 'faction_id': 59, 'rank': 6},
    "Reputation: Thorium Brotherhood (Exalted)": {'kind': 'reputation_rank', 'faction_id': 59, 'rank': 7},
    "Reputation: Undercity (Friendly)": {'kind': 'reputation_rank', 'faction_id': 68, 'rank': 4},
    "Reputation: Undercity (Honored)": {'kind': 'reputation_rank', 'faction_id': 68, 'rank': 5},
    "Reputation: Undercity (Revered)": {'kind': 'reputation_rank', 'faction_id': 68, 'rank': 6},
    "Reputation: Undercity (Exalted)": {'kind': 'reputation_rank', 'faction_id': 68, 'rank': 7},
    "Reputation: Darnassus (Friendly)": {'kind': 'reputation_rank', 'faction_id': 69, 'rank': 4},
    "Reputation: Darnassus (Honored)": {'kind': 'reputation_rank', 'faction_id': 69, 'rank': 5},
    "Reputation: Darnassus (Revered)": {'kind': 'reputation_rank', 'faction_id': 69, 'rank': 6},
    "Reputation: Darnassus (Exalted)": {'kind': 'reputation_rank', 'faction_id': 69, 'rank': 7},
    "Reputation: Syndicate (Hostile)": {'kind': 'reputation_rank', 'faction_id': 70, 'rank': 1},
    "Reputation: Syndicate (Unfriendly)": {'kind': 'reputation_rank', 'faction_id': 70, 'rank': 2},
    "Reputation: Syndicate (Neutral)": {'kind': 'reputation_rank', 'faction_id': 70, 'rank': 3},
    "Reputation: Syndicate (Friendly)": {'kind': 'reputation_rank', 'faction_id': 70, 'rank': 4},
    "Reputation: Syndicate (Honored)": {'kind': 'reputation_rank', 'faction_id': 70, 'rank': 5},
    "Reputation: Syndicate (Revered)": {'kind': 'reputation_rank', 'faction_id': 70, 'rank': 6},
    "Reputation: Syndicate (Exalted)": {'kind': 'reputation_rank', 'faction_id': 70, 'rank': 7},
    "Reputation: Stormwind (Friendly)": {'kind': 'reputation_rank', 'faction_id': 72, 'rank': 4},
    "Reputation: Stormwind (Honored)": {'kind': 'reputation_rank', 'faction_id': 72, 'rank': 5},
    "Reputation: Stormwind (Revered)": {'kind': 'reputation_rank', 'faction_id': 72, 'rank': 6},
    "Reputation: Stormwind (Exalted)": {'kind': 'reputation_rank', 'faction_id': 72, 'rank': 7},
    "Reputation: Orgrimmar (Friendly)": {'kind': 'reputation_rank', 'faction_id': 76, 'rank': 4},
    "Reputation: Orgrimmar (Honored)": {'kind': 'reputation_rank', 'faction_id': 76, 'rank': 5},
    "Reputation: Orgrimmar (Revered)": {'kind': 'reputation_rank', 'faction_id': 76, 'rank': 6},
    "Reputation: Orgrimmar (Exalted)": {'kind': 'reputation_rank', 'faction_id': 76, 'rank': 7},
    "Reputation: Thunder Bluff (Friendly)": {'kind': 'reputation_rank', 'faction_id': 81, 'rank': 4},
    "Reputation: Thunder Bluff (Honored)": {'kind': 'reputation_rank', 'faction_id': 81, 'rank': 5},
    "Reputation: Thunder Bluff (Revered)": {'kind': 'reputation_rank', 'faction_id': 81, 'rank': 6},
    "Reputation: Thunder Bluff (Exalted)": {'kind': 'reputation_rank', 'faction_id': 81, 'rank': 7},
    "Reputation: Bloodsail Buccaneers (Hostile)": {'kind': 'reputation_rank', 'faction_id': 87, 'rank': 1},
    "Reputation: Bloodsail Buccaneers (Unfriendly)": {'kind': 'reputation_rank', 'faction_id': 87, 'rank': 2},
    "Reputation: Bloodsail Buccaneers (Neutral)": {'kind': 'reputation_rank', 'faction_id': 87, 'rank': 3},
    "Reputation: Bloodsail Buccaneers (Friendly)": {'kind': 'reputation_rank', 'faction_id': 87, 'rank': 4},
    "Reputation: Bloodsail Buccaneers (Honored)": {'kind': 'reputation_rank', 'faction_id': 87, 'rank': 5},
    "Reputation: Bloodsail Buccaneers (Revered)": {'kind': 'reputation_rank', 'faction_id': 87, 'rank': 6},
    "Reputation: Bloodsail Buccaneers (Exalted)": {'kind': 'reputation_rank', 'faction_id': 87, 'rank': 7},
    "Reputation: Gelkis Clan Centaur (Friendly)": {'kind': 'reputation_rank', 'faction_id': 92, 'rank': 4},
    "Reputation: Gelkis Clan Centaur (Honored)": {'kind': 'reputation_rank', 'faction_id': 92, 'rank': 5},
    "Reputation: Gelkis Clan Centaur (Revered)": {'kind': 'reputation_rank', 'faction_id': 92, 'rank': 6},
    "Reputation: Gelkis Clan Centaur (Exalted)": {'kind': 'reputation_rank', 'faction_id': 92, 'rank': 7},
    "Reputation: Magram Clan Centaur (Friendly)": {'kind': 'reputation_rank', 'faction_id': 93, 'rank': 4},
    "Reputation: Magram Clan Centaur (Honored)": {'kind': 'reputation_rank', 'faction_id': 93, 'rank': 5},
    "Reputation: Magram Clan Centaur (Revered)": {'kind': 'reputation_rank', 'faction_id': 93, 'rank': 6},
    "Reputation: Magram Clan Centaur (Exalted)": {'kind': 'reputation_rank', 'faction_id': 93, 'rank': 7},
    "Reputation: Steamwheedle Cartel (Friendly)": {'kind': 'reputation_rank', 'faction_id': 169, 'rank': 4},
    "Reputation: Steamwheedle Cartel (Honored)": {'kind': 'reputation_rank', 'faction_id': 169, 'rank': 5},
    "Reputation: Steamwheedle Cartel (Revered)": {'kind': 'reputation_rank', 'faction_id': 169, 'rank': 6},
    "Reputation: Steamwheedle Cartel (Exalted)": {'kind': 'reputation_rank', 'faction_id': 169, 'rank': 7},
    "Reputation: Zandalar Tribe (Friendly)": {'kind': 'reputation_rank', 'faction_id': 270, 'rank': 4},
    "Reputation: Zandalar Tribe (Honored)": {'kind': 'reputation_rank', 'faction_id': 270, 'rank': 5},
    "Reputation: Zandalar Tribe (Revered)": {'kind': 'reputation_rank', 'faction_id': 270, 'rank': 6},
    "Reputation: Zandalar Tribe (Exalted)": {'kind': 'reputation_rank', 'faction_id': 270, 'rank': 7},
    "Reputation: Ravenholdt (Friendly)": {'kind': 'reputation_rank', 'faction_id': 349, 'rank': 4},
    "Reputation: Ravenholdt (Honored)": {'kind': 'reputation_rank', 'faction_id': 349, 'rank': 5},
    "Reputation: Ravenholdt (Revered)": {'kind': 'reputation_rank', 'faction_id': 349, 'rank': 6},
    "Reputation: Ravenholdt (Exalted)": {'kind': 'reputation_rank', 'faction_id': 349, 'rank': 7},
    "Reputation: Gadgetzan (Friendly)": {'kind': 'reputation_rank', 'faction_id': 369, 'rank': 4},
    "Reputation: Gadgetzan (Honored)": {'kind': 'reputation_rank', 'faction_id': 369, 'rank': 5},
    "Reputation: Gadgetzan (Revered)": {'kind': 'reputation_rank', 'faction_id': 369, 'rank': 6},
    "Reputation: Gadgetzan (Exalted)": {'kind': 'reputation_rank', 'faction_id': 369, 'rank': 7},
    "Reputation: Ratchet (Friendly)": {'kind': 'reputation_rank', 'faction_id': 470, 'rank': 4},
    "Reputation: Ratchet (Honored)": {'kind': 'reputation_rank', 'faction_id': 470, 'rank': 5},
    "Reputation: Ratchet (Revered)": {'kind': 'reputation_rank', 'faction_id': 470, 'rank': 6},
    "Reputation: Ratchet (Exalted)": {'kind': 'reputation_rank', 'faction_id': 470, 'rank': 7},
    "Reputation: Wildhammer Clan (Friendly)": {'kind': 'reputation_rank', 'faction_id': 471, 'rank': 4},
    "Reputation: Wildhammer Clan (Honored)": {'kind': 'reputation_rank', 'faction_id': 471, 'rank': 5},
    "Reputation: Wildhammer Clan (Revered)": {'kind': 'reputation_rank', 'faction_id': 471, 'rank': 6},
    "Reputation: Wildhammer Clan (Exalted)": {'kind': 'reputation_rank', 'faction_id': 471, 'rank': 7},
    "Reputation: The League of Arathor (Friendly)": {'kind': 'reputation_rank', 'faction_id': 509, 'rank': 4},
    "Reputation: The League of Arathor (Honored)": {'kind': 'reputation_rank', 'faction_id': 509, 'rank': 5},
    "Reputation: The League of Arathor (Revered)": {'kind': 'reputation_rank', 'faction_id': 509, 'rank': 6},
    "Reputation: The League of Arathor (Exalted)": {'kind': 'reputation_rank', 'faction_id': 509, 'rank': 7},
    "Reputation: The Defilers (Friendly)": {'kind': 'reputation_rank', 'faction_id': 510, 'rank': 4},
    "Reputation: The Defilers (Honored)": {'kind': 'reputation_rank', 'faction_id': 510, 'rank': 5},
    "Reputation: The Defilers (Revered)": {'kind': 'reputation_rank', 'faction_id': 510, 'rank': 6},
    "Reputation: The Defilers (Exalted)": {'kind': 'reputation_rank', 'faction_id': 510, 'rank': 7},
    "Reputation: Argent Dawn (Friendly)": {'kind': 'reputation_rank', 'faction_id': 529, 'rank': 4},
    "Reputation: Argent Dawn (Honored)": {'kind': 'reputation_rank', 'faction_id': 529, 'rank': 5},
    "Reputation: Argent Dawn (Revered)": {'kind': 'reputation_rank', 'faction_id': 529, 'rank': 6},
    "Reputation: Argent Dawn (Exalted)": {'kind': 'reputation_rank', 'faction_id': 529, 'rank': 7},
    "Reputation: Darkspear Trolls (Friendly)": {'kind': 'reputation_rank', 'faction_id': 530, 'rank': 4},
    "Reputation: Darkspear Trolls (Honored)": {'kind': 'reputation_rank', 'faction_id': 530, 'rank': 5},
    "Reputation: Darkspear Trolls (Revered)": {'kind': 'reputation_rank', 'faction_id': 530, 'rank': 6},
    "Reputation: Darkspear Trolls (Exalted)": {'kind': 'reputation_rank', 'faction_id': 530, 'rank': 7},
    "Reputation: Caer Darrow (Friendly)": {'kind': 'reputation_rank', 'faction_id': 574, 'rank': 4},
    "Reputation: Caer Darrow (Honored)": {'kind': 'reputation_rank', 'faction_id': 574, 'rank': 5},
    "Reputation: Caer Darrow (Revered)": {'kind': 'reputation_rank', 'faction_id': 574, 'rank': 6},
    "Reputation: Caer Darrow (Exalted)": {'kind': 'reputation_rank', 'faction_id': 574, 'rank': 7},
    "Reputation: Timbermaw Hold (Unfriendly)": {'kind': 'reputation_rank', 'faction_id': 576, 'rank': 2},
    "Reputation: Timbermaw Hold (Neutral)": {'kind': 'reputation_rank', 'faction_id': 576, 'rank': 3},
    "Reputation: Timbermaw Hold (Friendly)": {'kind': 'reputation_rank', 'faction_id': 576, 'rank': 4},
    "Reputation: Timbermaw Hold (Honored)": {'kind': 'reputation_rank', 'faction_id': 576, 'rank': 5},
    "Reputation: Timbermaw Hold (Revered)": {'kind': 'reputation_rank', 'faction_id': 576, 'rank': 6},
    "Reputation: Timbermaw Hold (Exalted)": {'kind': 'reputation_rank', 'faction_id': 576, 'rank': 7},
    "Reputation: Everlook (Friendly)": {'kind': 'reputation_rank', 'faction_id': 577, 'rank': 4},
    "Reputation: Everlook (Honored)": {'kind': 'reputation_rank', 'faction_id': 577, 'rank': 5},
    "Reputation: Everlook (Revered)": {'kind': 'reputation_rank', 'faction_id': 577, 'rank': 6},
    "Reputation: Everlook (Exalted)": {'kind': 'reputation_rank', 'faction_id': 577, 'rank': 7},
    "Reputation: Wintersaber Trainers (Hostile)": {'kind': 'reputation_rank', 'faction_id': 589, 'rank': 1},
    "Reputation: Wintersaber Trainers (Unfriendly)": {'kind': 'reputation_rank', 'faction_id': 589, 'rank': 2},
    "Reputation: Wintersaber Trainers (Neutral)": {'kind': 'reputation_rank', 'faction_id': 589, 'rank': 3},
    "Reputation: Wintersaber Trainers (Friendly)": {'kind': 'reputation_rank', 'faction_id': 589, 'rank': 4},
    "Reputation: Wintersaber Trainers (Honored)": {'kind': 'reputation_rank', 'faction_id': 589, 'rank': 5},
    "Reputation: Wintersaber Trainers (Revered)": {'kind': 'reputation_rank', 'faction_id': 589, 'rank': 6},
    "Reputation: Wintersaber Trainers (Exalted)": {'kind': 'reputation_rank', 'faction_id': 589, 'rank': 7},
    "Reputation: Cenarion Circle (Friendly)": {'kind': 'reputation_rank', 'faction_id': 609, 'rank': 4},
    "Reputation: Cenarion Circle (Honored)": {'kind': 'reputation_rank', 'faction_id': 609, 'rank': 5},
    "Reputation: Cenarion Circle (Revered)": {'kind': 'reputation_rank', 'faction_id': 609, 'rank': 6},
    "Reputation: Cenarion Circle (Exalted)": {'kind': 'reputation_rank', 'faction_id': 609, 'rank': 7},
    "Reputation: Frostwolf Clan (Friendly)": {'kind': 'reputation_rank', 'faction_id': 729, 'rank': 4},
    "Reputation: Frostwolf Clan (Honored)": {'kind': 'reputation_rank', 'faction_id': 729, 'rank': 5},
    "Reputation: Frostwolf Clan (Revered)": {'kind': 'reputation_rank', 'faction_id': 729, 'rank': 6},
    "Reputation: Frostwolf Clan (Exalted)": {'kind': 'reputation_rank', 'faction_id': 729, 'rank': 7},
    "Reputation: Stormpike Guard (Friendly)": {'kind': 'reputation_rank', 'faction_id': 730, 'rank': 4},
    "Reputation: Stormpike Guard (Honored)": {'kind': 'reputation_rank', 'faction_id': 730, 'rank': 5},
    "Reputation: Stormpike Guard (Revered)": {'kind': 'reputation_rank', 'faction_id': 730, 'rank': 6},
    "Reputation: Stormpike Guard (Exalted)": {'kind': 'reputation_rank', 'faction_id': 730, 'rank': 7},
    "Reputation: Hydraxian Waterlords (Friendly)": {'kind': 'reputation_rank', 'faction_id': 749, 'rank': 4},
    "Reputation: Hydraxian Waterlords (Honored)": {'kind': 'reputation_rank', 'faction_id': 749, 'rank': 5},
    "Reputation: Hydraxian Waterlords (Revered)": {'kind': 'reputation_rank', 'faction_id': 749, 'rank': 6},
    "Reputation: Hydraxian Waterlords (Exalted)": {'kind': 'reputation_rank', 'faction_id': 749, 'rank': 7},
    "Reputation: Shen'dralar (Friendly)": {'kind': 'reputation_rank', 'faction_id': 809, 'rank': 4},
    "Reputation: Shen'dralar (Honored)": {'kind': 'reputation_rank', 'faction_id': 809, 'rank': 5},
    "Reputation: Shen'dralar (Revered)": {'kind': 'reputation_rank', 'faction_id': 809, 'rank': 6},
    "Reputation: Shen'dralar (Exalted)": {'kind': 'reputation_rank', 'faction_id': 809, 'rank': 7},
    "Reputation: Warsong Outriders (Friendly)": {'kind': 'reputation_rank', 'faction_id': 889, 'rank': 4},
    "Reputation: Warsong Outriders (Honored)": {'kind': 'reputation_rank', 'faction_id': 889, 'rank': 5},
    "Reputation: Warsong Outriders (Revered)": {'kind': 'reputation_rank', 'faction_id': 889, 'rank': 6},
    "Reputation: Warsong Outriders (Exalted)": {'kind': 'reputation_rank', 'faction_id': 889, 'rank': 7},
    "Reputation: Silverwing Sentinels (Friendly)": {'kind': 'reputation_rank', 'faction_id': 890, 'rank': 4},
    "Reputation: Silverwing Sentinels (Honored)": {'kind': 'reputation_rank', 'faction_id': 890, 'rank': 5},
    "Reputation: Silverwing Sentinels (Revered)": {'kind': 'reputation_rank', 'faction_id': 890, 'rank': 6},
    "Reputation: Silverwing Sentinels (Exalted)": {'kind': 'reputation_rank', 'faction_id': 890, 'rank': 7},
    "Reputation: Darkmoon Faire (Friendly)": {'kind': 'reputation_rank', 'faction_id': 909, 'rank': 4},
    "Reputation: Darkmoon Faire (Honored)": {'kind': 'reputation_rank', 'faction_id': 909, 'rank': 5},
    "Reputation: Darkmoon Faire (Revered)": {'kind': 'reputation_rank', 'faction_id': 909, 'rank': 6},
    "Reputation: Darkmoon Faire (Exalted)": {'kind': 'reputation_rank', 'faction_id': 909, 'rank': 7},
    "Reputation: Brood of Nozdormu (Hostile)": {'kind': 'reputation_rank', 'faction_id': 910, 'rank': 1},
    "Reputation: Brood of Nozdormu (Unfriendly)": {'kind': 'reputation_rank', 'faction_id': 910, 'rank': 2},
    "Reputation: Brood of Nozdormu (Neutral)": {'kind': 'reputation_rank', 'faction_id': 910, 'rank': 3},
    "Reputation: Brood of Nozdormu (Friendly)": {'kind': 'reputation_rank', 'faction_id': 910, 'rank': 4},
    "Reputation: Brood of Nozdormu (Honored)": {'kind': 'reputation_rank', 'faction_id': 910, 'rank': 5},
    "Reputation: Brood of Nozdormu (Revered)": {'kind': 'reputation_rank', 'faction_id': 910, 'rank': 6},
    "Reputation: Brood of Nozdormu (Exalted)": {'kind': 'reputation_rank', 'faction_id': 910, 'rank': 7},
    "Reputation: Silvermoon City (Friendly)": {'kind': 'reputation_rank', 'faction_id': 911, 'rank': 4},
    "Reputation: Silvermoon City (Honored)": {'kind': 'reputation_rank', 'faction_id': 911, 'rank': 5},
    "Reputation: Silvermoon City (Revered)": {'kind': 'reputation_rank', 'faction_id': 911, 'rank': 6},
    "Reputation: Silvermoon City (Exalted)": {'kind': 'reputation_rank', 'faction_id': 911, 'rank': 7},
    "Reputation: Tranquillien (Friendly)": {'kind': 'reputation_rank', 'faction_id': 922, 'rank': 4},
    "Reputation: Tranquillien (Honored)": {'kind': 'reputation_rank', 'faction_id': 922, 'rank': 5},
    "Reputation: Tranquillien (Revered)": {'kind': 'reputation_rank', 'faction_id': 922, 'rank': 6},
    "Reputation: Tranquillien (Exalted)": {'kind': 'reputation_rank', 'faction_id': 922, 'rank': 7},
    "Reputation: Exodar (Friendly)": {'kind': 'reputation_rank', 'faction_id': 930, 'rank': 4},
    "Reputation: Exodar (Honored)": {'kind': 'reputation_rank', 'faction_id': 930, 'rank': 5},
    "Reputation: Exodar (Revered)": {'kind': 'reputation_rank', 'faction_id': 930, 'rank': 6},
    "Reputation: Exodar (Exalted)": {'kind': 'reputation_rank', 'faction_id': 930, 'rank': 7},
    "Reputation: The Aldor (Unfriendly)": {'kind': 'reputation_rank', 'faction_id': 932, 'rank': 2},
    "Reputation: The Aldor (Neutral)": {'kind': 'reputation_rank', 'faction_id': 932, 'rank': 3},
    "Reputation: The Aldor (Friendly)": {'kind': 'reputation_rank', 'faction_id': 932, 'rank': 4},
    "Reputation: The Aldor (Honored)": {'kind': 'reputation_rank', 'faction_id': 932, 'rank': 5},
    "Reputation: The Aldor (Revered)": {'kind': 'reputation_rank', 'faction_id': 932, 'rank': 6},
    "Reputation: The Aldor (Exalted)": {'kind': 'reputation_rank', 'faction_id': 932, 'rank': 7},
    "Reputation: The Consortium (Friendly)": {'kind': 'reputation_rank', 'faction_id': 933, 'rank': 4},
    "Reputation: The Consortium (Honored)": {'kind': 'reputation_rank', 'faction_id': 933, 'rank': 5},
    "Reputation: The Consortium (Revered)": {'kind': 'reputation_rank', 'faction_id': 933, 'rank': 6},
    "Reputation: The Consortium (Exalted)": {'kind': 'reputation_rank', 'faction_id': 933, 'rank': 7},
    "Reputation: The Scryers (Unfriendly)": {'kind': 'reputation_rank', 'faction_id': 934, 'rank': 2},
    "Reputation: The Scryers (Neutral)": {'kind': 'reputation_rank', 'faction_id': 934, 'rank': 3},
    "Reputation: The Scryers (Friendly)": {'kind': 'reputation_rank', 'faction_id': 934, 'rank': 4},
    "Reputation: The Scryers (Honored)": {'kind': 'reputation_rank', 'faction_id': 934, 'rank': 5},
    "Reputation: The Scryers (Revered)": {'kind': 'reputation_rank', 'faction_id': 934, 'rank': 6},
    "Reputation: The Scryers (Exalted)": {'kind': 'reputation_rank', 'faction_id': 934, 'rank': 7},
    "Reputation: The Sha'tar (Friendly)": {'kind': 'reputation_rank', 'faction_id': 935, 'rank': 4},
    "Reputation: The Sha'tar (Honored)": {'kind': 'reputation_rank', 'faction_id': 935, 'rank': 5},
    "Reputation: The Sha'tar (Revered)": {'kind': 'reputation_rank', 'faction_id': 935, 'rank': 6},
    "Reputation: The Sha'tar (Exalted)": {'kind': 'reputation_rank', 'faction_id': 935, 'rank': 7},
    "Reputation: Shattrath City (Friendly)": {'kind': 'reputation_rank', 'faction_id': 936, 'rank': 4},
    "Reputation: Shattrath City (Honored)": {'kind': 'reputation_rank', 'faction_id': 936, 'rank': 5},
    "Reputation: Shattrath City (Revered)": {'kind': 'reputation_rank', 'faction_id': 936, 'rank': 6},
    "Reputation: Shattrath City (Exalted)": {'kind': 'reputation_rank', 'faction_id': 936, 'rank': 7},
    "Reputation: The Mag'har (Neutral)": {'kind': 'reputation_rank', 'faction_id': 941, 'rank': 3},
    "Reputation: The Mag'har (Friendly)": {'kind': 'reputation_rank', 'faction_id': 941, 'rank': 4},
    "Reputation: The Mag'har (Honored)": {'kind': 'reputation_rank', 'faction_id': 941, 'rank': 5},
    "Reputation: The Mag'har (Revered)": {'kind': 'reputation_rank', 'faction_id': 941, 'rank': 6},
    "Reputation: The Mag'har (Exalted)": {'kind': 'reputation_rank', 'faction_id': 941, 'rank': 7},
    "Reputation: Cenarion Expedition (Friendly)": {'kind': 'reputation_rank', 'faction_id': 942, 'rank': 4},
    "Reputation: Cenarion Expedition (Honored)": {'kind': 'reputation_rank', 'faction_id': 942, 'rank': 5},
    "Reputation: Cenarion Expedition (Revered)": {'kind': 'reputation_rank', 'faction_id': 942, 'rank': 6},
    "Reputation: Cenarion Expedition (Exalted)": {'kind': 'reputation_rank', 'faction_id': 942, 'rank': 7},
    "Reputation: Honor Hold (Friendly)": {'kind': 'reputation_rank', 'faction_id': 946, 'rank': 4},
    "Reputation: Honor Hold (Honored)": {'kind': 'reputation_rank', 'faction_id': 946, 'rank': 5},
    "Reputation: Honor Hold (Revered)": {'kind': 'reputation_rank', 'faction_id': 946, 'rank': 6},
    "Reputation: Honor Hold (Exalted)": {'kind': 'reputation_rank', 'faction_id': 946, 'rank': 7},
    "Reputation: Thrallmar (Friendly)": {'kind': 'reputation_rank', 'faction_id': 947, 'rank': 4},
    "Reputation: Thrallmar (Honored)": {'kind': 'reputation_rank', 'faction_id': 947, 'rank': 5},
    "Reputation: Thrallmar (Revered)": {'kind': 'reputation_rank', 'faction_id': 947, 'rank': 6},
    "Reputation: Thrallmar (Exalted)": {'kind': 'reputation_rank', 'faction_id': 947, 'rank': 7},
    "Reputation: The Violet Eye (Friendly)": {'kind': 'reputation_rank', 'faction_id': 967, 'rank': 4},
    "Reputation: The Violet Eye (Honored)": {'kind': 'reputation_rank', 'faction_id': 967, 'rank': 5},
    "Reputation: The Violet Eye (Revered)": {'kind': 'reputation_rank', 'faction_id': 967, 'rank': 6},
    "Reputation: The Violet Eye (Exalted)": {'kind': 'reputation_rank', 'faction_id': 967, 'rank': 7},
    "Reputation: Sporeggar (Neutral)": {'kind': 'reputation_rank', 'faction_id': 970, 'rank': 3},
    "Reputation: Sporeggar (Friendly)": {'kind': 'reputation_rank', 'faction_id': 970, 'rank': 4},
    "Reputation: Sporeggar (Honored)": {'kind': 'reputation_rank', 'faction_id': 970, 'rank': 5},
    "Reputation: Sporeggar (Revered)": {'kind': 'reputation_rank', 'faction_id': 970, 'rank': 6},
    "Reputation: Sporeggar (Exalted)": {'kind': 'reputation_rank', 'faction_id': 970, 'rank': 7},
    "Reputation: Kurenai (Neutral)": {'kind': 'reputation_rank', 'faction_id': 978, 'rank': 3},
    "Reputation: Kurenai (Friendly)": {'kind': 'reputation_rank', 'faction_id': 978, 'rank': 4},
    "Reputation: Kurenai (Honored)": {'kind': 'reputation_rank', 'faction_id': 978, 'rank': 5},
    "Reputation: Kurenai (Revered)": {'kind': 'reputation_rank', 'faction_id': 978, 'rank': 6},
    "Reputation: Kurenai (Exalted)": {'kind': 'reputation_rank', 'faction_id': 978, 'rank': 7},
    "Reputation: Keepers of Time (Friendly)": {'kind': 'reputation_rank', 'faction_id': 989, 'rank': 4},
    "Reputation: Keepers of Time (Honored)": {'kind': 'reputation_rank', 'faction_id': 989, 'rank': 5},
    "Reputation: Keepers of Time (Revered)": {'kind': 'reputation_rank', 'faction_id': 989, 'rank': 6},
    "Reputation: Keepers of Time (Exalted)": {'kind': 'reputation_rank', 'faction_id': 989, 'rank': 7},
    "Reputation: The Scale of the Sands (Friendly)": {'kind': 'reputation_rank', 'faction_id': 990, 'rank': 4},
    "Reputation: The Scale of the Sands (Honored)": {'kind': 'reputation_rank', 'faction_id': 990, 'rank': 5},
    "Reputation: The Scale of the Sands (Revered)": {'kind': 'reputation_rank', 'faction_id': 990, 'rank': 6},
    "Reputation: The Scale of the Sands (Exalted)": {'kind': 'reputation_rank', 'faction_id': 990, 'rank': 7},
    "Reputation: Lower City (Friendly)": {'kind': 'reputation_rank', 'faction_id': 1011, 'rank': 4},
    "Reputation: Lower City (Honored)": {'kind': 'reputation_rank', 'faction_id': 1011, 'rank': 5},
    "Reputation: Lower City (Revered)": {'kind': 'reputation_rank', 'faction_id': 1011, 'rank': 6},
    "Reputation: Lower City (Exalted)": {'kind': 'reputation_rank', 'faction_id': 1011, 'rank': 7},
    "Reputation: Ashtongue Deathsworn (Friendly)": {'kind': 'reputation_rank', 'faction_id': 1012, 'rank': 4},
    "Reputation: Ashtongue Deathsworn (Honored)": {'kind': 'reputation_rank', 'faction_id': 1012, 'rank': 5},
    "Reputation: Ashtongue Deathsworn (Revered)": {'kind': 'reputation_rank', 'faction_id': 1012, 'rank': 6},
    "Reputation: Ashtongue Deathsworn (Exalted)": {'kind': 'reputation_rank', 'faction_id': 1012, 'rank': 7},
    "Reputation: Netherwing (Hostile)": {'kind': 'reputation_rank', 'faction_id': 1015, 'rank': 1},
    "Reputation: Netherwing (Unfriendly)": {'kind': 'reputation_rank', 'faction_id': 1015, 'rank': 2},
    "Reputation: Netherwing (Neutral)": {'kind': 'reputation_rank', 'faction_id': 1015, 'rank': 3},
    "Reputation: Netherwing (Friendly)": {'kind': 'reputation_rank', 'faction_id': 1015, 'rank': 4},
    "Reputation: Netherwing (Honored)": {'kind': 'reputation_rank', 'faction_id': 1015, 'rank': 5},
    "Reputation: Netherwing (Revered)": {'kind': 'reputation_rank', 'faction_id': 1015, 'rank': 6},
    "Reputation: Netherwing (Exalted)": {'kind': 'reputation_rank', 'faction_id': 1015, 'rank': 7},
    "Reputation: Sha'tari Skyguard (Friendly)": {'kind': 'reputation_rank', 'faction_id': 1031, 'rank': 4},
    "Reputation: Sha'tari Skyguard (Honored)": {'kind': 'reputation_rank', 'faction_id': 1031, 'rank': 5},
    "Reputation: Sha'tari Skyguard (Revered)": {'kind': 'reputation_rank', 'faction_id': 1031, 'rank': 6},
    "Reputation: Sha'tari Skyguard (Exalted)": {'kind': 'reputation_rank', 'faction_id': 1031, 'rank': 7},
    "Reputation: Alliance Vanguard (Friendly)": {'kind': 'reputation_rank', 'faction_id': 1037, 'rank': 4},
    "Reputation: Alliance Vanguard (Honored)": {'kind': 'reputation_rank', 'faction_id': 1037, 'rank': 5},
    "Reputation: Alliance Vanguard (Revered)": {'kind': 'reputation_rank', 'faction_id': 1037, 'rank': 6},
    "Reputation: Alliance Vanguard (Exalted)": {'kind': 'reputation_rank', 'faction_id': 1037, 'rank': 7},
    "Reputation: Ogri'la (Friendly)": {'kind': 'reputation_rank', 'faction_id': 1038, 'rank': 4},
    "Reputation: Ogri'la (Honored)": {'kind': 'reputation_rank', 'faction_id': 1038, 'rank': 5},
    "Reputation: Ogri'la (Revered)": {'kind': 'reputation_rank', 'faction_id': 1038, 'rank': 6},
    "Reputation: Ogri'la (Exalted)": {'kind': 'reputation_rank', 'faction_id': 1038, 'rank': 7},
    "Reputation: Valiance Expedition (Friendly)": {'kind': 'reputation_rank', 'faction_id': 1050, 'rank': 4},
    "Reputation: Valiance Expedition (Honored)": {'kind': 'reputation_rank', 'faction_id': 1050, 'rank': 5},
    "Reputation: Valiance Expedition (Revered)": {'kind': 'reputation_rank', 'faction_id': 1050, 'rank': 6},
    "Reputation: Valiance Expedition (Exalted)": {'kind': 'reputation_rank', 'faction_id': 1050, 'rank': 7},
    "Reputation: Horde Expedition (Friendly)": {'kind': 'reputation_rank', 'faction_id': 1052, 'rank': 4},
    "Reputation: Horde Expedition (Honored)": {'kind': 'reputation_rank', 'faction_id': 1052, 'rank': 5},
    "Reputation: Horde Expedition (Revered)": {'kind': 'reputation_rank', 'faction_id': 1052, 'rank': 6},
    "Reputation: Horde Expedition (Exalted)": {'kind': 'reputation_rank', 'faction_id': 1052, 'rank': 7},
    "Reputation: The Taunka (Friendly)": {'kind': 'reputation_rank', 'faction_id': 1064, 'rank': 4},
    "Reputation: The Taunka (Honored)": {'kind': 'reputation_rank', 'faction_id': 1064, 'rank': 5},
    "Reputation: The Taunka (Revered)": {'kind': 'reputation_rank', 'faction_id': 1064, 'rank': 6},
    "Reputation: The Taunka (Exalted)": {'kind': 'reputation_rank', 'faction_id': 1064, 'rank': 7},
    "Reputation: The Hand of Vengeance (Friendly)": {'kind': 'reputation_rank', 'faction_id': 1067, 'rank': 4},
    "Reputation: The Hand of Vengeance (Honored)": {'kind': 'reputation_rank', 'faction_id': 1067, 'rank': 5},
    "Reputation: The Hand of Vengeance (Revered)": {'kind': 'reputation_rank', 'faction_id': 1067, 'rank': 6},
    "Reputation: The Hand of Vengeance (Exalted)": {'kind': 'reputation_rank', 'faction_id': 1067, 'rank': 7},
    "Reputation: Explorers' League (Friendly)": {'kind': 'reputation_rank', 'faction_id': 1068, 'rank': 4},
    "Reputation: Explorers' League (Honored)": {'kind': 'reputation_rank', 'faction_id': 1068, 'rank': 5},
    "Reputation: Explorers' League (Revered)": {'kind': 'reputation_rank', 'faction_id': 1068, 'rank': 6},
    "Reputation: Explorers' League (Exalted)": {'kind': 'reputation_rank', 'faction_id': 1068, 'rank': 7},
    "Reputation: The Kalu'ak (Friendly)": {'kind': 'reputation_rank', 'faction_id': 1073, 'rank': 4},
    "Reputation: The Kalu'ak (Honored)": {'kind': 'reputation_rank', 'faction_id': 1073, 'rank': 5},
    "Reputation: The Kalu'ak (Revered)": {'kind': 'reputation_rank', 'faction_id': 1073, 'rank': 6},
    "Reputation: The Kalu'ak (Exalted)": {'kind': 'reputation_rank', 'faction_id': 1073, 'rank': 7},
    "Reputation: Shattered Sun Offensive (Friendly)": {'kind': 'reputation_rank', 'faction_id': 1077, 'rank': 4},
    "Reputation: Shattered Sun Offensive (Honored)": {'kind': 'reputation_rank', 'faction_id': 1077, 'rank': 5},
    "Reputation: Shattered Sun Offensive (Revered)": {'kind': 'reputation_rank', 'faction_id': 1077, 'rank': 6},
    "Reputation: Shattered Sun Offensive (Exalted)": {'kind': 'reputation_rank', 'faction_id': 1077, 'rank': 7},
    "Reputation: Warsong Offensive (Friendly)": {'kind': 'reputation_rank', 'faction_id': 1085, 'rank': 4},
    "Reputation: Warsong Offensive (Honored)": {'kind': 'reputation_rank', 'faction_id': 1085, 'rank': 5},
    "Reputation: Warsong Offensive (Revered)": {'kind': 'reputation_rank', 'faction_id': 1085, 'rank': 6},
    "Reputation: Warsong Offensive (Exalted)": {'kind': 'reputation_rank', 'faction_id': 1085, 'rank': 7},
    "Reputation: Kirin Tor (Friendly)": {'kind': 'reputation_rank', 'faction_id': 1090, 'rank': 4},
    "Reputation: Kirin Tor (Honored)": {'kind': 'reputation_rank', 'faction_id': 1090, 'rank': 5},
    "Reputation: Kirin Tor (Revered)": {'kind': 'reputation_rank', 'faction_id': 1090, 'rank': 6},
    "Reputation: Kirin Tor (Exalted)": {'kind': 'reputation_rank', 'faction_id': 1090, 'rank': 7},
    "Reputation: The Wyrmrest Accord (Friendly)": {'kind': 'reputation_rank', 'faction_id': 1091, 'rank': 4},
    "Reputation: The Wyrmrest Accord (Honored)": {'kind': 'reputation_rank', 'faction_id': 1091, 'rank': 5},
    "Reputation: The Wyrmrest Accord (Revered)": {'kind': 'reputation_rank', 'faction_id': 1091, 'rank': 6},
    "Reputation: The Wyrmrest Accord (Exalted)": {'kind': 'reputation_rank', 'faction_id': 1091, 'rank': 7},
    "Reputation: The Silver Covenant (Friendly)": {'kind': 'reputation_rank', 'faction_id': 1094, 'rank': 4},
    "Reputation: The Silver Covenant (Honored)": {'kind': 'reputation_rank', 'faction_id': 1094, 'rank': 5},
    "Reputation: The Silver Covenant (Revered)": {'kind': 'reputation_rank', 'faction_id': 1094, 'rank': 6},
    "Reputation: The Silver Covenant (Exalted)": {'kind': 'reputation_rank', 'faction_id': 1094, 'rank': 7},
    "Reputation: Knights of the Ebon Blade (Friendly)": {'kind': 'reputation_rank', 'faction_id': 1098, 'rank': 4},
    "Reputation: Knights of the Ebon Blade (Honored)": {'kind': 'reputation_rank', 'faction_id': 1098, 'rank': 5},
    "Reputation: Knights of the Ebon Blade (Revered)": {'kind': 'reputation_rank', 'faction_id': 1098, 'rank': 6},
    "Reputation: Knights of the Ebon Blade (Exalted)": {'kind': 'reputation_rank', 'faction_id': 1098, 'rank': 7},
    "Reputation: Frenzyheart Tribe (Friendly)": {'kind': 'reputation_rank', 'faction_id': 1104, 'rank': 4},
    "Reputation: Frenzyheart Tribe (Honored)": {'kind': 'reputation_rank', 'faction_id': 1104, 'rank': 5},
    "Reputation: Frenzyheart Tribe (Revered)": {'kind': 'reputation_rank', 'faction_id': 1104, 'rank': 6},
    "Reputation: Frenzyheart Tribe (Exalted)": {'kind': 'reputation_rank', 'faction_id': 1104, 'rank': 7},
    "Reputation: The Oracles (Friendly)": {'kind': 'reputation_rank', 'faction_id': 1105, 'rank': 4},
    "Reputation: The Oracles (Honored)": {'kind': 'reputation_rank', 'faction_id': 1105, 'rank': 5},
    "Reputation: The Oracles (Revered)": {'kind': 'reputation_rank', 'faction_id': 1105, 'rank': 6},
    "Reputation: The Oracles (Exalted)": {'kind': 'reputation_rank', 'faction_id': 1105, 'rank': 7},
    "Reputation: Argent Crusade (Friendly)": {'kind': 'reputation_rank', 'faction_id': 1106, 'rank': 4},
    "Reputation: Argent Crusade (Honored)": {'kind': 'reputation_rank', 'faction_id': 1106, 'rank': 5},
    "Reputation: Argent Crusade (Revered)": {'kind': 'reputation_rank', 'faction_id': 1106, 'rank': 6},
    "Reputation: Argent Crusade (Exalted)": {'kind': 'reputation_rank', 'faction_id': 1106, 'rank': 7},
    "Reputation: The Sons of Hodir (Hostile)": {'kind': 'reputation_rank', 'faction_id': 1119, 'rank': 1},
    "Reputation: The Sons of Hodir (Unfriendly)": {'kind': 'reputation_rank', 'faction_id': 1119, 'rank': 2},
    "Reputation: The Sons of Hodir (Neutral)": {'kind': 'reputation_rank', 'faction_id': 1119, 'rank': 3},
    "Reputation: The Sons of Hodir (Friendly)": {'kind': 'reputation_rank', 'faction_id': 1119, 'rank': 4},
    "Reputation: The Sons of Hodir (Honored)": {'kind': 'reputation_rank', 'faction_id': 1119, 'rank': 5},
    "Reputation: The Sons of Hodir (Revered)": {'kind': 'reputation_rank', 'faction_id': 1119, 'rank': 6},
    "Reputation: The Sons of Hodir (Exalted)": {'kind': 'reputation_rank', 'faction_id': 1119, 'rank': 7},
    "Reputation: The Sunreavers (Friendly)": {'kind': 'reputation_rank', 'faction_id': 1124, 'rank': 4},
    "Reputation: The Sunreavers (Honored)": {'kind': 'reputation_rank', 'faction_id': 1124, 'rank': 5},
    "Reputation: The Sunreavers (Revered)": {'kind': 'reputation_rank', 'faction_id': 1124, 'rank': 6},
    "Reputation: The Sunreavers (Exalted)": {'kind': 'reputation_rank', 'faction_id': 1124, 'rank': 7},
    "Reputation: The Frostborn (Friendly)": {'kind': 'reputation_rank', 'faction_id': 1126, 'rank': 4},
    "Reputation: The Frostborn (Honored)": {'kind': 'reputation_rank', 'faction_id': 1126, 'rank': 5},
    "Reputation: The Frostborn (Revered)": {'kind': 'reputation_rank', 'faction_id': 1126, 'rank': 6},
    "Reputation: The Frostborn (Exalted)": {'kind': 'reputation_rank', 'faction_id': 1126, 'rank': 7},
    "Reputation: The Ashen Verdict (Friendly)": {'kind': 'reputation_rank', 'faction_id': 1156, 'rank': 4},
    "Reputation: The Ashen Verdict (Honored)": {'kind': 'reputation_rank', 'faction_id': 1156, 'rank': 5},
    "Reputation: The Ashen Verdict (Revered)": {'kind': 'reputation_rank', 'faction_id': 1156, 'rank': 6},
    "Reputation: The Ashen Verdict (Exalted)": {'kind': 'reputation_rank', 'faction_id': 1156, 'rank': 7},
}

TAGS: dict[str, dict[str, frozenset[str]]] = {
    "Reputation: Booty Bay (Friendly)": {"expansion": frozenset({"vanilla"}), "rank_tier": frozenset({"standard"})},
    "Reputation: Booty Bay (Honored)": {"expansion": frozenset({"vanilla"}), "rank_tier": frozenset({"standard"})},
    "Reputation: Booty Bay (Revered)": {"expansion": frozenset({"vanilla"}), "rank_tier": frozenset({"standard"})},
    "Reputation: Booty Bay (Exalted)": {"expansion": frozenset({"vanilla"}), "rank_tier": frozenset({"standard"})},
    "Reputation: Ironforge (Friendly)": {"expansion": frozenset({"vanilla"}), "rank_tier": frozenset({"standard"})},
    "Reputation: Ironforge (Honored)": {"expansion": frozenset({"vanilla"}), "rank_tier": frozenset({"standard"})},
    "Reputation: Ironforge (Revered)": {"expansion": frozenset({"vanilla"}), "rank_tier": frozenset({"standard"})},
    "Reputation: Ironforge (Exalted)": {"expansion": frozenset({"vanilla"}), "rank_tier": frozenset({"standard"})},
    "Reputation: Gnomeregan Exiles (Friendly)": {"expansion": frozenset({"vanilla"}), "rank_tier": frozenset({"standard"})},
    "Reputation: Gnomeregan Exiles (Honored)": {"expansion": frozenset({"vanilla"}), "rank_tier": frozenset({"standard"})},
    "Reputation: Gnomeregan Exiles (Revered)": {"expansion": frozenset({"vanilla"}), "rank_tier": frozenset({"standard"})},
    "Reputation: Gnomeregan Exiles (Exalted)": {"expansion": frozenset({"vanilla"}), "rank_tier": frozenset({"standard"})},
    "Reputation: Thorium Brotherhood (Friendly)": {"expansion": frozenset({"vanilla"}), "rank_tier": frozenset({"standard"})},
    "Reputation: Thorium Brotherhood (Honored)": {"expansion": frozenset({"vanilla"}), "rank_tier": frozenset({"standard"})},
    "Reputation: Thorium Brotherhood (Revered)": {"expansion": frozenset({"vanilla"}), "rank_tier": frozenset({"standard"})},
    "Reputation: Thorium Brotherhood (Exalted)": {"expansion": frozenset({"vanilla"}), "rank_tier": frozenset({"standard"})},
    "Reputation: Undercity (Friendly)": {"expansion": frozenset({"vanilla"}), "rank_tier": frozenset({"standard"})},
    "Reputation: Undercity (Honored)": {"expansion": frozenset({"vanilla"}), "rank_tier": frozenset({"standard"})},
    "Reputation: Undercity (Revered)": {"expansion": frozenset({"vanilla"}), "rank_tier": frozenset({"standard"})},
    "Reputation: Undercity (Exalted)": {"expansion": frozenset({"vanilla"}), "rank_tier": frozenset({"standard"})},
    "Reputation: Darnassus (Friendly)": {"expansion": frozenset({"vanilla"}), "rank_tier": frozenset({"standard"})},
    "Reputation: Darnassus (Honored)": {"expansion": frozenset({"vanilla"}), "rank_tier": frozenset({"standard"})},
    "Reputation: Darnassus (Revered)": {"expansion": frozenset({"vanilla"}), "rank_tier": frozenset({"standard"})},
    "Reputation: Darnassus (Exalted)": {"expansion": frozenset({"vanilla"}), "rank_tier": frozenset({"standard"})},
    "Reputation: Syndicate (Hostile)": {"expansion": frozenset({"vanilla"}), "rank_tier": frozenset({"negative"})},
    "Reputation: Syndicate (Unfriendly)": {"expansion": frozenset({"vanilla"}), "rank_tier": frozenset({"negative"})},
    "Reputation: Syndicate (Neutral)": {"expansion": frozenset({"vanilla"}), "rank_tier": frozenset({"standard"})},
    "Reputation: Syndicate (Friendly)": {"expansion": frozenset({"vanilla"}), "rank_tier": frozenset({"standard"})},
    "Reputation: Syndicate (Honored)": {"expansion": frozenset({"vanilla"}), "rank_tier": frozenset({"standard"})},
    "Reputation: Syndicate (Revered)": {"expansion": frozenset({"vanilla"}), "rank_tier": frozenset({"standard"})},
    "Reputation: Syndicate (Exalted)": {"expansion": frozenset({"vanilla"}), "rank_tier": frozenset({"standard"})},
    "Reputation: Stormwind (Friendly)": {"expansion": frozenset({"vanilla"}), "rank_tier": frozenset({"standard"})},
    "Reputation: Stormwind (Honored)": {"expansion": frozenset({"vanilla"}), "rank_tier": frozenset({"standard"})},
    "Reputation: Stormwind (Revered)": {"expansion": frozenset({"vanilla"}), "rank_tier": frozenset({"standard"})},
    "Reputation: Stormwind (Exalted)": {"expansion": frozenset({"vanilla"}), "rank_tier": frozenset({"standard"})},
    "Reputation: Orgrimmar (Friendly)": {"expansion": frozenset({"vanilla"}), "rank_tier": frozenset({"standard"})},
    "Reputation: Orgrimmar (Honored)": {"expansion": frozenset({"vanilla"}), "rank_tier": frozenset({"standard"})},
    "Reputation: Orgrimmar (Revered)": {"expansion": frozenset({"vanilla"}), "rank_tier": frozenset({"standard"})},
    "Reputation: Orgrimmar (Exalted)": {"expansion": frozenset({"vanilla"}), "rank_tier": frozenset({"standard"})},
    "Reputation: Thunder Bluff (Friendly)": {"expansion": frozenset({"vanilla"}), "rank_tier": frozenset({"standard"})},
    "Reputation: Thunder Bluff (Honored)": {"expansion": frozenset({"vanilla"}), "rank_tier": frozenset({"standard"})},
    "Reputation: Thunder Bluff (Revered)": {"expansion": frozenset({"vanilla"}), "rank_tier": frozenset({"standard"})},
    "Reputation: Thunder Bluff (Exalted)": {"expansion": frozenset({"vanilla"}), "rank_tier": frozenset({"standard"})},
    "Reputation: Bloodsail Buccaneers (Hostile)": {"expansion": frozenset({"vanilla"}), "rank_tier": frozenset({"negative"})},
    "Reputation: Bloodsail Buccaneers (Unfriendly)": {"expansion": frozenset({"vanilla"}), "rank_tier": frozenset({"negative"})},
    "Reputation: Bloodsail Buccaneers (Neutral)": {"expansion": frozenset({"vanilla"}), "rank_tier": frozenset({"standard"})},
    "Reputation: Bloodsail Buccaneers (Friendly)": {"expansion": frozenset({"vanilla"}), "rank_tier": frozenset({"standard"})},
    "Reputation: Bloodsail Buccaneers (Honored)": {"expansion": frozenset({"vanilla"}), "rank_tier": frozenset({"standard"})},
    "Reputation: Bloodsail Buccaneers (Revered)": {"expansion": frozenset({"vanilla"}), "rank_tier": frozenset({"standard"})},
    "Reputation: Bloodsail Buccaneers (Exalted)": {"expansion": frozenset({"vanilla"}), "rank_tier": frozenset({"standard"})},
    "Reputation: Gelkis Clan Centaur (Friendly)": {"expansion": frozenset({"vanilla"}), "rank_tier": frozenset({"standard"})},
    "Reputation: Gelkis Clan Centaur (Honored)": {"expansion": frozenset({"vanilla"}), "rank_tier": frozenset({"standard"})},
    "Reputation: Gelkis Clan Centaur (Revered)": {"expansion": frozenset({"vanilla"}), "rank_tier": frozenset({"standard"})},
    "Reputation: Gelkis Clan Centaur (Exalted)": {"expansion": frozenset({"vanilla"}), "rank_tier": frozenset({"standard"})},
    "Reputation: Magram Clan Centaur (Friendly)": {"expansion": frozenset({"vanilla"}), "rank_tier": frozenset({"standard"})},
    "Reputation: Magram Clan Centaur (Honored)": {"expansion": frozenset({"vanilla"}), "rank_tier": frozenset({"standard"})},
    "Reputation: Magram Clan Centaur (Revered)": {"expansion": frozenset({"vanilla"}), "rank_tier": frozenset({"standard"})},
    "Reputation: Magram Clan Centaur (Exalted)": {"expansion": frozenset({"vanilla"}), "rank_tier": frozenset({"standard"})},
    "Reputation: Steamwheedle Cartel (Friendly)": {"expansion": frozenset({"vanilla"}), "rank_tier": frozenset({"standard"})},
    "Reputation: Steamwheedle Cartel (Honored)": {"expansion": frozenset({"vanilla"}), "rank_tier": frozenset({"standard"})},
    "Reputation: Steamwheedle Cartel (Revered)": {"expansion": frozenset({"vanilla"}), "rank_tier": frozenset({"standard"})},
    "Reputation: Steamwheedle Cartel (Exalted)": {"expansion": frozenset({"vanilla"}), "rank_tier": frozenset({"standard"})},
    "Reputation: Zandalar Tribe (Friendly)": {"expansion": frozenset({"vanilla"}), "rank_tier": frozenset({"standard"})},
    "Reputation: Zandalar Tribe (Honored)": {"expansion": frozenset({"vanilla"}), "rank_tier": frozenset({"standard"})},
    "Reputation: Zandalar Tribe (Revered)": {"expansion": frozenset({"vanilla"}), "rank_tier": frozenset({"standard"})},
    "Reputation: Zandalar Tribe (Exalted)": {"expansion": frozenset({"vanilla"}), "rank_tier": frozenset({"standard"})},
    "Reputation: Ravenholdt (Friendly)": {"expansion": frozenset({"vanilla"}), "rank_tier": frozenset({"standard"})},
    "Reputation: Ravenholdt (Honored)": {"expansion": frozenset({"vanilla"}), "rank_tier": frozenset({"standard"})},
    "Reputation: Ravenholdt (Revered)": {"expansion": frozenset({"vanilla"}), "rank_tier": frozenset({"standard"})},
    "Reputation: Ravenholdt (Exalted)": {"expansion": frozenset({"vanilla"}), "rank_tier": frozenset({"standard"})},
    "Reputation: Gadgetzan (Friendly)": {"expansion": frozenset({"vanilla"}), "rank_tier": frozenset({"standard"})},
    "Reputation: Gadgetzan (Honored)": {"expansion": frozenset({"vanilla"}), "rank_tier": frozenset({"standard"})},
    "Reputation: Gadgetzan (Revered)": {"expansion": frozenset({"vanilla"}), "rank_tier": frozenset({"standard"})},
    "Reputation: Gadgetzan (Exalted)": {"expansion": frozenset({"vanilla"}), "rank_tier": frozenset({"standard"})},
    "Reputation: Ratchet (Friendly)": {"expansion": frozenset({"vanilla"}), "rank_tier": frozenset({"standard"})},
    "Reputation: Ratchet (Honored)": {"expansion": frozenset({"vanilla"}), "rank_tier": frozenset({"standard"})},
    "Reputation: Ratchet (Revered)": {"expansion": frozenset({"vanilla"}), "rank_tier": frozenset({"standard"})},
    "Reputation: Ratchet (Exalted)": {"expansion": frozenset({"vanilla"}), "rank_tier": frozenset({"standard"})},
    "Reputation: Wildhammer Clan (Friendly)": {"expansion": frozenset({"vanilla"}), "rank_tier": frozenset({"standard"})},
    "Reputation: Wildhammer Clan (Honored)": {"expansion": frozenset({"vanilla"}), "rank_tier": frozenset({"standard"})},
    "Reputation: Wildhammer Clan (Revered)": {"expansion": frozenset({"vanilla"}), "rank_tier": frozenset({"standard"})},
    "Reputation: Wildhammer Clan (Exalted)": {"expansion": frozenset({"vanilla"}), "rank_tier": frozenset({"standard"})},
    "Reputation: The League of Arathor (Friendly)": {"expansion": frozenset({"vanilla"}), "rank_tier": frozenset({"standard"})},
    "Reputation: The League of Arathor (Honored)": {"expansion": frozenset({"vanilla"}), "rank_tier": frozenset({"standard"})},
    "Reputation: The League of Arathor (Revered)": {"expansion": frozenset({"vanilla"}), "rank_tier": frozenset({"standard"})},
    "Reputation: The League of Arathor (Exalted)": {"expansion": frozenset({"vanilla"}), "rank_tier": frozenset({"standard"})},
    "Reputation: The Defilers (Friendly)": {"expansion": frozenset({"vanilla"}), "rank_tier": frozenset({"standard"})},
    "Reputation: The Defilers (Honored)": {"expansion": frozenset({"vanilla"}), "rank_tier": frozenset({"standard"})},
    "Reputation: The Defilers (Revered)": {"expansion": frozenset({"vanilla"}), "rank_tier": frozenset({"standard"})},
    "Reputation: The Defilers (Exalted)": {"expansion": frozenset({"vanilla"}), "rank_tier": frozenset({"standard"})},
    "Reputation: Argent Dawn (Friendly)": {"expansion": frozenset({"vanilla"}), "rank_tier": frozenset({"standard"})},
    "Reputation: Argent Dawn (Honored)": {"expansion": frozenset({"vanilla"}), "rank_tier": frozenset({"standard"})},
    "Reputation: Argent Dawn (Revered)": {"expansion": frozenset({"vanilla"}), "rank_tier": frozenset({"standard"})},
    "Reputation: Argent Dawn (Exalted)": {"expansion": frozenset({"vanilla"}), "rank_tier": frozenset({"standard"})},
    "Reputation: Darkspear Trolls (Friendly)": {"expansion": frozenset({"vanilla"}), "rank_tier": frozenset({"standard"})},
    "Reputation: Darkspear Trolls (Honored)": {"expansion": frozenset({"vanilla"}), "rank_tier": frozenset({"standard"})},
    "Reputation: Darkspear Trolls (Revered)": {"expansion": frozenset({"vanilla"}), "rank_tier": frozenset({"standard"})},
    "Reputation: Darkspear Trolls (Exalted)": {"expansion": frozenset({"vanilla"}), "rank_tier": frozenset({"standard"})},
    "Reputation: Caer Darrow (Friendly)": {"expansion": frozenset({"vanilla"}), "rank_tier": frozenset({"standard"})},
    "Reputation: Caer Darrow (Honored)": {"expansion": frozenset({"vanilla"}), "rank_tier": frozenset({"standard"})},
    "Reputation: Caer Darrow (Revered)": {"expansion": frozenset({"vanilla"}), "rank_tier": frozenset({"standard"})},
    "Reputation: Caer Darrow (Exalted)": {"expansion": frozenset({"vanilla"}), "rank_tier": frozenset({"standard"})},
    "Reputation: Timbermaw Hold (Unfriendly)": {"expansion": frozenset({"vanilla"}), "rank_tier": frozenset({"negative"})},
    "Reputation: Timbermaw Hold (Neutral)": {"expansion": frozenset({"vanilla"}), "rank_tier": frozenset({"standard"})},
    "Reputation: Timbermaw Hold (Friendly)": {"expansion": frozenset({"vanilla"}), "rank_tier": frozenset({"standard"})},
    "Reputation: Timbermaw Hold (Honored)": {"expansion": frozenset({"vanilla"}), "rank_tier": frozenset({"standard"})},
    "Reputation: Timbermaw Hold (Revered)": {"expansion": frozenset({"vanilla"}), "rank_tier": frozenset({"standard"})},
    "Reputation: Timbermaw Hold (Exalted)": {"expansion": frozenset({"vanilla"}), "rank_tier": frozenset({"standard"})},
    "Reputation: Everlook (Friendly)": {"expansion": frozenset({"vanilla"}), "rank_tier": frozenset({"standard"})},
    "Reputation: Everlook (Honored)": {"expansion": frozenset({"vanilla"}), "rank_tier": frozenset({"standard"})},
    "Reputation: Everlook (Revered)": {"expansion": frozenset({"vanilla"}), "rank_tier": frozenset({"standard"})},
    "Reputation: Everlook (Exalted)": {"expansion": frozenset({"vanilla"}), "rank_tier": frozenset({"standard"})},
    "Reputation: Wintersaber Trainers (Hostile)": {"expansion": frozenset({"vanilla"}), "rank_tier": frozenset({"negative"})},
    "Reputation: Wintersaber Trainers (Unfriendly)": {"expansion": frozenset({"vanilla"}), "rank_tier": frozenset({"negative"})},
    "Reputation: Wintersaber Trainers (Neutral)": {"expansion": frozenset({"vanilla"}), "rank_tier": frozenset({"standard"})},
    "Reputation: Wintersaber Trainers (Friendly)": {"expansion": frozenset({"vanilla"}), "rank_tier": frozenset({"standard"})},
    "Reputation: Wintersaber Trainers (Honored)": {"expansion": frozenset({"vanilla"}), "rank_tier": frozenset({"standard"})},
    "Reputation: Wintersaber Trainers (Revered)": {"expansion": frozenset({"vanilla"}), "rank_tier": frozenset({"standard"})},
    "Reputation: Wintersaber Trainers (Exalted)": {"expansion": frozenset({"vanilla"}), "rank_tier": frozenset({"standard"})},
    "Reputation: Cenarion Circle (Friendly)": {"expansion": frozenset({"vanilla"}), "rank_tier": frozenset({"standard"})},
    "Reputation: Cenarion Circle (Honored)": {"expansion": frozenset({"vanilla"}), "rank_tier": frozenset({"standard"})},
    "Reputation: Cenarion Circle (Revered)": {"expansion": frozenset({"vanilla"}), "rank_tier": frozenset({"standard"})},
    "Reputation: Cenarion Circle (Exalted)": {"expansion": frozenset({"vanilla"}), "rank_tier": frozenset({"standard"})},
    "Reputation: Frostwolf Clan (Friendly)": {"expansion": frozenset({"vanilla"}), "rank_tier": frozenset({"standard"})},
    "Reputation: Frostwolf Clan (Honored)": {"expansion": frozenset({"vanilla"}), "rank_tier": frozenset({"standard"})},
    "Reputation: Frostwolf Clan (Revered)": {"expansion": frozenset({"vanilla"}), "rank_tier": frozenset({"standard"})},
    "Reputation: Frostwolf Clan (Exalted)": {"expansion": frozenset({"vanilla"}), "rank_tier": frozenset({"standard"})},
    "Reputation: Stormpike Guard (Friendly)": {"expansion": frozenset({"vanilla"}), "rank_tier": frozenset({"standard"})},
    "Reputation: Stormpike Guard (Honored)": {"expansion": frozenset({"vanilla"}), "rank_tier": frozenset({"standard"})},
    "Reputation: Stormpike Guard (Revered)": {"expansion": frozenset({"vanilla"}), "rank_tier": frozenset({"standard"})},
    "Reputation: Stormpike Guard (Exalted)": {"expansion": frozenset({"vanilla"}), "rank_tier": frozenset({"standard"})},
    "Reputation: Hydraxian Waterlords (Friendly)": {"expansion": frozenset({"vanilla"}), "rank_tier": frozenset({"standard"})},
    "Reputation: Hydraxian Waterlords (Honored)": {"expansion": frozenset({"vanilla"}), "rank_tier": frozenset({"standard"})},
    "Reputation: Hydraxian Waterlords (Revered)": {"expansion": frozenset({"vanilla"}), "rank_tier": frozenset({"standard"})},
    "Reputation: Hydraxian Waterlords (Exalted)": {"expansion": frozenset({"vanilla"}), "rank_tier": frozenset({"standard"})},
    "Reputation: Shen'dralar (Friendly)": {"expansion": frozenset({"vanilla"}), "rank_tier": frozenset({"standard"})},
    "Reputation: Shen'dralar (Honored)": {"expansion": frozenset({"vanilla"}), "rank_tier": frozenset({"standard"})},
    "Reputation: Shen'dralar (Revered)": {"expansion": frozenset({"vanilla"}), "rank_tier": frozenset({"standard"})},
    "Reputation: Shen'dralar (Exalted)": {"expansion": frozenset({"vanilla"}), "rank_tier": frozenset({"standard"})},
    "Reputation: Warsong Outriders (Friendly)": {"expansion": frozenset({"vanilla"}), "rank_tier": frozenset({"standard"})},
    "Reputation: Warsong Outriders (Honored)": {"expansion": frozenset({"vanilla"}), "rank_tier": frozenset({"standard"})},
    "Reputation: Warsong Outriders (Revered)": {"expansion": frozenset({"vanilla"}), "rank_tier": frozenset({"standard"})},
    "Reputation: Warsong Outriders (Exalted)": {"expansion": frozenset({"vanilla"}), "rank_tier": frozenset({"standard"})},
    "Reputation: Silverwing Sentinels (Friendly)": {"expansion": frozenset({"vanilla"}), "rank_tier": frozenset({"standard"})},
    "Reputation: Silverwing Sentinels (Honored)": {"expansion": frozenset({"vanilla"}), "rank_tier": frozenset({"standard"})},
    "Reputation: Silverwing Sentinels (Revered)": {"expansion": frozenset({"vanilla"}), "rank_tier": frozenset({"standard"})},
    "Reputation: Silverwing Sentinels (Exalted)": {"expansion": frozenset({"vanilla"}), "rank_tier": frozenset({"standard"})},
    "Reputation: Darkmoon Faire (Friendly)": {"expansion": frozenset({"vanilla"}), "rank_tier": frozenset({"standard"})},
    "Reputation: Darkmoon Faire (Honored)": {"expansion": frozenset({"vanilla"}), "rank_tier": frozenset({"standard"})},
    "Reputation: Darkmoon Faire (Revered)": {"expansion": frozenset({"vanilla"}), "rank_tier": frozenset({"standard"})},
    "Reputation: Darkmoon Faire (Exalted)": {"expansion": frozenset({"vanilla"}), "rank_tier": frozenset({"standard"})},
    "Reputation: Brood of Nozdormu (Hostile)": {"expansion": frozenset({"vanilla"}), "rank_tier": frozenset({"negative"})},
    "Reputation: Brood of Nozdormu (Unfriendly)": {"expansion": frozenset({"vanilla"}), "rank_tier": frozenset({"negative"})},
    "Reputation: Brood of Nozdormu (Neutral)": {"expansion": frozenset({"vanilla"}), "rank_tier": frozenset({"standard"})},
    "Reputation: Brood of Nozdormu (Friendly)": {"expansion": frozenset({"vanilla"}), "rank_tier": frozenset({"standard"})},
    "Reputation: Brood of Nozdormu (Honored)": {"expansion": frozenset({"vanilla"}), "rank_tier": frozenset({"standard"})},
    "Reputation: Brood of Nozdormu (Revered)": {"expansion": frozenset({"vanilla"}), "rank_tier": frozenset({"standard"})},
    "Reputation: Brood of Nozdormu (Exalted)": {"expansion": frozenset({"vanilla"}), "rank_tier": frozenset({"standard"})},
    "Reputation: Silvermoon City (Friendly)": {"expansion": frozenset({"tbc"}), "rank_tier": frozenset({"standard"})},
    "Reputation: Silvermoon City (Honored)": {"expansion": frozenset({"tbc"}), "rank_tier": frozenset({"standard"})},
    "Reputation: Silvermoon City (Revered)": {"expansion": frozenset({"tbc"}), "rank_tier": frozenset({"standard"})},
    "Reputation: Silvermoon City (Exalted)": {"expansion": frozenset({"tbc"}), "rank_tier": frozenset({"standard"})},
    "Reputation: Tranquillien (Friendly)": {"expansion": frozenset({"tbc"}), "rank_tier": frozenset({"standard"})},
    "Reputation: Tranquillien (Honored)": {"expansion": frozenset({"tbc"}), "rank_tier": frozenset({"standard"})},
    "Reputation: Tranquillien (Revered)": {"expansion": frozenset({"tbc"}), "rank_tier": frozenset({"standard"})},
    "Reputation: Tranquillien (Exalted)": {"expansion": frozenset({"tbc"}), "rank_tier": frozenset({"standard"})},
    "Reputation: Exodar (Friendly)": {"expansion": frozenset({"tbc"}), "rank_tier": frozenset({"standard"})},
    "Reputation: Exodar (Honored)": {"expansion": frozenset({"tbc"}), "rank_tier": frozenset({"standard"})},
    "Reputation: Exodar (Revered)": {"expansion": frozenset({"tbc"}), "rank_tier": frozenset({"standard"})},
    "Reputation: Exodar (Exalted)": {"expansion": frozenset({"tbc"}), "rank_tier": frozenset({"standard"})},
    "Reputation: The Aldor (Unfriendly)": {"expansion": frozenset({"tbc"}), "rank_tier": frozenset({"negative"})},
    "Reputation: The Aldor (Neutral)": {"expansion": frozenset({"tbc"}), "rank_tier": frozenset({"standard"})},
    "Reputation: The Aldor (Friendly)": {"expansion": frozenset({"tbc"}), "rank_tier": frozenset({"standard"})},
    "Reputation: The Aldor (Honored)": {"expansion": frozenset({"tbc"}), "rank_tier": frozenset({"standard"})},
    "Reputation: The Aldor (Revered)": {"expansion": frozenset({"tbc"}), "rank_tier": frozenset({"standard"})},
    "Reputation: The Aldor (Exalted)": {"expansion": frozenset({"tbc"}), "rank_tier": frozenset({"standard"})},
    "Reputation: The Consortium (Friendly)": {"expansion": frozenset({"tbc"}), "rank_tier": frozenset({"standard"})},
    "Reputation: The Consortium (Honored)": {"expansion": frozenset({"tbc"}), "rank_tier": frozenset({"standard"})},
    "Reputation: The Consortium (Revered)": {"expansion": frozenset({"tbc"}), "rank_tier": frozenset({"standard"})},
    "Reputation: The Consortium (Exalted)": {"expansion": frozenset({"tbc"}), "rank_tier": frozenset({"standard"})},
    "Reputation: The Scryers (Unfriendly)": {"expansion": frozenset({"tbc"}), "rank_tier": frozenset({"negative"})},
    "Reputation: The Scryers (Neutral)": {"expansion": frozenset({"tbc"}), "rank_tier": frozenset({"standard"})},
    "Reputation: The Scryers (Friendly)": {"expansion": frozenset({"tbc"}), "rank_tier": frozenset({"standard"})},
    "Reputation: The Scryers (Honored)": {"expansion": frozenset({"tbc"}), "rank_tier": frozenset({"standard"})},
    "Reputation: The Scryers (Revered)": {"expansion": frozenset({"tbc"}), "rank_tier": frozenset({"standard"})},
    "Reputation: The Scryers (Exalted)": {"expansion": frozenset({"tbc"}), "rank_tier": frozenset({"standard"})},
    "Reputation: The Sha'tar (Friendly)": {"expansion": frozenset({"tbc"}), "rank_tier": frozenset({"standard"})},
    "Reputation: The Sha'tar (Honored)": {"expansion": frozenset({"tbc"}), "rank_tier": frozenset({"standard"})},
    "Reputation: The Sha'tar (Revered)": {"expansion": frozenset({"tbc"}), "rank_tier": frozenset({"standard"})},
    "Reputation: The Sha'tar (Exalted)": {"expansion": frozenset({"tbc"}), "rank_tier": frozenset({"standard"})},
    "Reputation: Shattrath City (Friendly)": {"expansion": frozenset({"tbc"}), "rank_tier": frozenset({"standard"})},
    "Reputation: Shattrath City (Honored)": {"expansion": frozenset({"tbc"}), "rank_tier": frozenset({"standard"})},
    "Reputation: Shattrath City (Revered)": {"expansion": frozenset({"tbc"}), "rank_tier": frozenset({"standard"})},
    "Reputation: Shattrath City (Exalted)": {"expansion": frozenset({"tbc"}), "rank_tier": frozenset({"standard"})},
    "Reputation: The Mag'har (Neutral)": {"expansion": frozenset({"tbc"}), "rank_tier": frozenset({"standard"})},
    "Reputation: The Mag'har (Friendly)": {"expansion": frozenset({"tbc"}), "rank_tier": frozenset({"standard"})},
    "Reputation: The Mag'har (Honored)": {"expansion": frozenset({"tbc"}), "rank_tier": frozenset({"standard"})},
    "Reputation: The Mag'har (Revered)": {"expansion": frozenset({"tbc"}), "rank_tier": frozenset({"standard"})},
    "Reputation: The Mag'har (Exalted)": {"expansion": frozenset({"tbc"}), "rank_tier": frozenset({"standard"})},
    "Reputation: Cenarion Expedition (Friendly)": {"expansion": frozenset({"tbc"}), "rank_tier": frozenset({"standard"})},
    "Reputation: Cenarion Expedition (Honored)": {"expansion": frozenset({"tbc"}), "rank_tier": frozenset({"standard"})},
    "Reputation: Cenarion Expedition (Revered)": {"expansion": frozenset({"tbc"}), "rank_tier": frozenset({"standard"})},
    "Reputation: Cenarion Expedition (Exalted)": {"expansion": frozenset({"tbc"}), "rank_tier": frozenset({"standard"})},
    "Reputation: Honor Hold (Friendly)": {"expansion": frozenset({"tbc"}), "rank_tier": frozenset({"standard"})},
    "Reputation: Honor Hold (Honored)": {"expansion": frozenset({"tbc"}), "rank_tier": frozenset({"standard"})},
    "Reputation: Honor Hold (Revered)": {"expansion": frozenset({"tbc"}), "rank_tier": frozenset({"standard"})},
    "Reputation: Honor Hold (Exalted)": {"expansion": frozenset({"tbc"}), "rank_tier": frozenset({"standard"})},
    "Reputation: Thrallmar (Friendly)": {"expansion": frozenset({"tbc"}), "rank_tier": frozenset({"standard"})},
    "Reputation: Thrallmar (Honored)": {"expansion": frozenset({"tbc"}), "rank_tier": frozenset({"standard"})},
    "Reputation: Thrallmar (Revered)": {"expansion": frozenset({"tbc"}), "rank_tier": frozenset({"standard"})},
    "Reputation: Thrallmar (Exalted)": {"expansion": frozenset({"tbc"}), "rank_tier": frozenset({"standard"})},
    "Reputation: The Violet Eye (Friendly)": {"expansion": frozenset({"tbc"}), "rank_tier": frozenset({"standard"})},
    "Reputation: The Violet Eye (Honored)": {"expansion": frozenset({"tbc"}), "rank_tier": frozenset({"standard"})},
    "Reputation: The Violet Eye (Revered)": {"expansion": frozenset({"tbc"}), "rank_tier": frozenset({"standard"})},
    "Reputation: The Violet Eye (Exalted)": {"expansion": frozenset({"tbc"}), "rank_tier": frozenset({"standard"})},
    "Reputation: Sporeggar (Neutral)": {"expansion": frozenset({"tbc"}), "rank_tier": frozenset({"standard"})},
    "Reputation: Sporeggar (Friendly)": {"expansion": frozenset({"tbc"}), "rank_tier": frozenset({"standard"})},
    "Reputation: Sporeggar (Honored)": {"expansion": frozenset({"tbc"}), "rank_tier": frozenset({"standard"})},
    "Reputation: Sporeggar (Revered)": {"expansion": frozenset({"tbc"}), "rank_tier": frozenset({"standard"})},
    "Reputation: Sporeggar (Exalted)": {"expansion": frozenset({"tbc"}), "rank_tier": frozenset({"standard"})},
    "Reputation: Kurenai (Neutral)": {"expansion": frozenset({"tbc"}), "rank_tier": frozenset({"standard"})},
    "Reputation: Kurenai (Friendly)": {"expansion": frozenset({"tbc"}), "rank_tier": frozenset({"standard"})},
    "Reputation: Kurenai (Honored)": {"expansion": frozenset({"tbc"}), "rank_tier": frozenset({"standard"})},
    "Reputation: Kurenai (Revered)": {"expansion": frozenset({"tbc"}), "rank_tier": frozenset({"standard"})},
    "Reputation: Kurenai (Exalted)": {"expansion": frozenset({"tbc"}), "rank_tier": frozenset({"standard"})},
    "Reputation: Keepers of Time (Friendly)": {"expansion": frozenset({"tbc"}), "rank_tier": frozenset({"standard"})},
    "Reputation: Keepers of Time (Honored)": {"expansion": frozenset({"tbc"}), "rank_tier": frozenset({"standard"})},
    "Reputation: Keepers of Time (Revered)": {"expansion": frozenset({"tbc"}), "rank_tier": frozenset({"standard"})},
    "Reputation: Keepers of Time (Exalted)": {"expansion": frozenset({"tbc"}), "rank_tier": frozenset({"standard"})},
    "Reputation: The Scale of the Sands (Friendly)": {"expansion": frozenset({"tbc"}), "rank_tier": frozenset({"standard"})},
    "Reputation: The Scale of the Sands (Honored)": {"expansion": frozenset({"tbc"}), "rank_tier": frozenset({"standard"})},
    "Reputation: The Scale of the Sands (Revered)": {"expansion": frozenset({"tbc"}), "rank_tier": frozenset({"standard"})},
    "Reputation: The Scale of the Sands (Exalted)": {"expansion": frozenset({"tbc"}), "rank_tier": frozenset({"standard"})},
    "Reputation: Lower City (Friendly)": {"expansion": frozenset({"tbc"}), "rank_tier": frozenset({"standard"})},
    "Reputation: Lower City (Honored)": {"expansion": frozenset({"tbc"}), "rank_tier": frozenset({"standard"})},
    "Reputation: Lower City (Revered)": {"expansion": frozenset({"tbc"}), "rank_tier": frozenset({"standard"})},
    "Reputation: Lower City (Exalted)": {"expansion": frozenset({"tbc"}), "rank_tier": frozenset({"standard"})},
    "Reputation: Ashtongue Deathsworn (Friendly)": {"expansion": frozenset({"tbc"}), "rank_tier": frozenset({"standard"})},
    "Reputation: Ashtongue Deathsworn (Honored)": {"expansion": frozenset({"tbc"}), "rank_tier": frozenset({"standard"})},
    "Reputation: Ashtongue Deathsworn (Revered)": {"expansion": frozenset({"tbc"}), "rank_tier": frozenset({"standard"})},
    "Reputation: Ashtongue Deathsworn (Exalted)": {"expansion": frozenset({"tbc"}), "rank_tier": frozenset({"standard"})},
    "Reputation: Netherwing (Hostile)": {"expansion": frozenset({"tbc"}), "rank_tier": frozenset({"negative"})},
    "Reputation: Netherwing (Unfriendly)": {"expansion": frozenset({"tbc"}), "rank_tier": frozenset({"negative"})},
    "Reputation: Netherwing (Neutral)": {"expansion": frozenset({"tbc"}), "rank_tier": frozenset({"standard"})},
    "Reputation: Netherwing (Friendly)": {"expansion": frozenset({"tbc"}), "rank_tier": frozenset({"standard"})},
    "Reputation: Netherwing (Honored)": {"expansion": frozenset({"tbc"}), "rank_tier": frozenset({"standard"})},
    "Reputation: Netherwing (Revered)": {"expansion": frozenset({"tbc"}), "rank_tier": frozenset({"standard"})},
    "Reputation: Netherwing (Exalted)": {"expansion": frozenset({"tbc"}), "rank_tier": frozenset({"standard"})},
    "Reputation: Sha'tari Skyguard (Friendly)": {"expansion": frozenset({"tbc"}), "rank_tier": frozenset({"standard"})},
    "Reputation: Sha'tari Skyguard (Honored)": {"expansion": frozenset({"tbc"}), "rank_tier": frozenset({"standard"})},
    "Reputation: Sha'tari Skyguard (Revered)": {"expansion": frozenset({"tbc"}), "rank_tier": frozenset({"standard"})},
    "Reputation: Sha'tari Skyguard (Exalted)": {"expansion": frozenset({"tbc"}), "rank_tier": frozenset({"standard"})},
    "Reputation: Alliance Vanguard (Friendly)": {"expansion": frozenset({"wotlk"}), "rank_tier": frozenset({"standard"})},
    "Reputation: Alliance Vanguard (Honored)": {"expansion": frozenset({"wotlk"}), "rank_tier": frozenset({"standard"})},
    "Reputation: Alliance Vanguard (Revered)": {"expansion": frozenset({"wotlk"}), "rank_tier": frozenset({"standard"})},
    "Reputation: Alliance Vanguard (Exalted)": {"expansion": frozenset({"wotlk"}), "rank_tier": frozenset({"standard"})},
    "Reputation: Ogri'la (Friendly)": {"expansion": frozenset({"tbc"}), "rank_tier": frozenset({"standard"})},
    "Reputation: Ogri'la (Honored)": {"expansion": frozenset({"tbc"}), "rank_tier": frozenset({"standard"})},
    "Reputation: Ogri'la (Revered)": {"expansion": frozenset({"tbc"}), "rank_tier": frozenset({"standard"})},
    "Reputation: Ogri'la (Exalted)": {"expansion": frozenset({"tbc"}), "rank_tier": frozenset({"standard"})},
    "Reputation: Valiance Expedition (Friendly)": {"expansion": frozenset({"wotlk"}), "rank_tier": frozenset({"standard"})},
    "Reputation: Valiance Expedition (Honored)": {"expansion": frozenset({"wotlk"}), "rank_tier": frozenset({"standard"})},
    "Reputation: Valiance Expedition (Revered)": {"expansion": frozenset({"wotlk"}), "rank_tier": frozenset({"standard"})},
    "Reputation: Valiance Expedition (Exalted)": {"expansion": frozenset({"wotlk"}), "rank_tier": frozenset({"standard"})},
    "Reputation: Horde Expedition (Friendly)": {"expansion": frozenset({"wotlk"}), "rank_tier": frozenset({"standard"})},
    "Reputation: Horde Expedition (Honored)": {"expansion": frozenset({"wotlk"}), "rank_tier": frozenset({"standard"})},
    "Reputation: Horde Expedition (Revered)": {"expansion": frozenset({"wotlk"}), "rank_tier": frozenset({"standard"})},
    "Reputation: Horde Expedition (Exalted)": {"expansion": frozenset({"wotlk"}), "rank_tier": frozenset({"standard"})},
    "Reputation: The Taunka (Friendly)": {"expansion": frozenset({"wotlk"}), "rank_tier": frozenset({"standard"})},
    "Reputation: The Taunka (Honored)": {"expansion": frozenset({"wotlk"}), "rank_tier": frozenset({"standard"})},
    "Reputation: The Taunka (Revered)": {"expansion": frozenset({"wotlk"}), "rank_tier": frozenset({"standard"})},
    "Reputation: The Taunka (Exalted)": {"expansion": frozenset({"wotlk"}), "rank_tier": frozenset({"standard"})},
    "Reputation: The Hand of Vengeance (Friendly)": {"expansion": frozenset({"wotlk"}), "rank_tier": frozenset({"standard"})},
    "Reputation: The Hand of Vengeance (Honored)": {"expansion": frozenset({"wotlk"}), "rank_tier": frozenset({"standard"})},
    "Reputation: The Hand of Vengeance (Revered)": {"expansion": frozenset({"wotlk"}), "rank_tier": frozenset({"standard"})},
    "Reputation: The Hand of Vengeance (Exalted)": {"expansion": frozenset({"wotlk"}), "rank_tier": frozenset({"standard"})},
    "Reputation: Explorers' League (Friendly)": {"expansion": frozenset({"wotlk"}), "rank_tier": frozenset({"standard"})},
    "Reputation: Explorers' League (Honored)": {"expansion": frozenset({"wotlk"}), "rank_tier": frozenset({"standard"})},
    "Reputation: Explorers' League (Revered)": {"expansion": frozenset({"wotlk"}), "rank_tier": frozenset({"standard"})},
    "Reputation: Explorers' League (Exalted)": {"expansion": frozenset({"wotlk"}), "rank_tier": frozenset({"standard"})},
    "Reputation: The Kalu'ak (Friendly)": {"expansion": frozenset({"wotlk"}), "rank_tier": frozenset({"standard"})},
    "Reputation: The Kalu'ak (Honored)": {"expansion": frozenset({"wotlk"}), "rank_tier": frozenset({"standard"})},
    "Reputation: The Kalu'ak (Revered)": {"expansion": frozenset({"wotlk"}), "rank_tier": frozenset({"standard"})},
    "Reputation: The Kalu'ak (Exalted)": {"expansion": frozenset({"wotlk"}), "rank_tier": frozenset({"standard"})},
    "Reputation: Shattered Sun Offensive (Friendly)": {"expansion": frozenset({"tbc"}), "rank_tier": frozenset({"standard"})},
    "Reputation: Shattered Sun Offensive (Honored)": {"expansion": frozenset({"tbc"}), "rank_tier": frozenset({"standard"})},
    "Reputation: Shattered Sun Offensive (Revered)": {"expansion": frozenset({"tbc"}), "rank_tier": frozenset({"standard"})},
    "Reputation: Shattered Sun Offensive (Exalted)": {"expansion": frozenset({"tbc"}), "rank_tier": frozenset({"standard"})},
    "Reputation: Warsong Offensive (Friendly)": {"expansion": frozenset({"wotlk"}), "rank_tier": frozenset({"standard"})},
    "Reputation: Warsong Offensive (Honored)": {"expansion": frozenset({"wotlk"}), "rank_tier": frozenset({"standard"})},
    "Reputation: Warsong Offensive (Revered)": {"expansion": frozenset({"wotlk"}), "rank_tier": frozenset({"standard"})},
    "Reputation: Warsong Offensive (Exalted)": {"expansion": frozenset({"wotlk"}), "rank_tier": frozenset({"standard"})},
    "Reputation: Kirin Tor (Friendly)": {"expansion": frozenset({"wotlk"}), "rank_tier": frozenset({"standard"})},
    "Reputation: Kirin Tor (Honored)": {"expansion": frozenset({"wotlk"}), "rank_tier": frozenset({"standard"})},
    "Reputation: Kirin Tor (Revered)": {"expansion": frozenset({"wotlk"}), "rank_tier": frozenset({"standard"})},
    "Reputation: Kirin Tor (Exalted)": {"expansion": frozenset({"wotlk"}), "rank_tier": frozenset({"standard"})},
    "Reputation: The Wyrmrest Accord (Friendly)": {"expansion": frozenset({"wotlk"}), "rank_tier": frozenset({"standard"})},
    "Reputation: The Wyrmrest Accord (Honored)": {"expansion": frozenset({"wotlk"}), "rank_tier": frozenset({"standard"})},
    "Reputation: The Wyrmrest Accord (Revered)": {"expansion": frozenset({"wotlk"}), "rank_tier": frozenset({"standard"})},
    "Reputation: The Wyrmrest Accord (Exalted)": {"expansion": frozenset({"wotlk"}), "rank_tier": frozenset({"standard"})},
    "Reputation: The Silver Covenant (Friendly)": {"expansion": frozenset({"wotlk"}), "rank_tier": frozenset({"standard"})},
    "Reputation: The Silver Covenant (Honored)": {"expansion": frozenset({"wotlk"}), "rank_tier": frozenset({"standard"})},
    "Reputation: The Silver Covenant (Revered)": {"expansion": frozenset({"wotlk"}), "rank_tier": frozenset({"standard"})},
    "Reputation: The Silver Covenant (Exalted)": {"expansion": frozenset({"wotlk"}), "rank_tier": frozenset({"standard"})},
    "Reputation: Knights of the Ebon Blade (Friendly)": {"expansion": frozenset({"wotlk"}), "rank_tier": frozenset({"standard"})},
    "Reputation: Knights of the Ebon Blade (Honored)": {"expansion": frozenset({"wotlk"}), "rank_tier": frozenset({"standard"})},
    "Reputation: Knights of the Ebon Blade (Revered)": {"expansion": frozenset({"wotlk"}), "rank_tier": frozenset({"standard"})},
    "Reputation: Knights of the Ebon Blade (Exalted)": {"expansion": frozenset({"wotlk"}), "rank_tier": frozenset({"standard"})},
    "Reputation: Frenzyheart Tribe (Friendly)": {"expansion": frozenset({"wotlk"}), "rank_tier": frozenset({"standard"})},
    "Reputation: Frenzyheart Tribe (Honored)": {"expansion": frozenset({"wotlk"}), "rank_tier": frozenset({"standard"})},
    "Reputation: Frenzyheart Tribe (Revered)": {"expansion": frozenset({"wotlk"}), "rank_tier": frozenset({"standard"})},
    "Reputation: Frenzyheart Tribe (Exalted)": {"expansion": frozenset({"wotlk"}), "rank_tier": frozenset({"standard"})},
    "Reputation: The Oracles (Friendly)": {"expansion": frozenset({"wotlk"}), "rank_tier": frozenset({"standard"})},
    "Reputation: The Oracles (Honored)": {"expansion": frozenset({"wotlk"}), "rank_tier": frozenset({"standard"})},
    "Reputation: The Oracles (Revered)": {"expansion": frozenset({"wotlk"}), "rank_tier": frozenset({"standard"})},
    "Reputation: The Oracles (Exalted)": {"expansion": frozenset({"wotlk"}), "rank_tier": frozenset({"standard"})},
    "Reputation: Argent Crusade (Friendly)": {"expansion": frozenset({"wotlk"}), "rank_tier": frozenset({"standard"})},
    "Reputation: Argent Crusade (Honored)": {"expansion": frozenset({"wotlk"}), "rank_tier": frozenset({"standard"})},
    "Reputation: Argent Crusade (Revered)": {"expansion": frozenset({"wotlk"}), "rank_tier": frozenset({"standard"})},
    "Reputation: Argent Crusade (Exalted)": {"expansion": frozenset({"wotlk"}), "rank_tier": frozenset({"standard"})},
    "Reputation: The Sons of Hodir (Hostile)": {"expansion": frozenset({"wotlk"}), "rank_tier": frozenset({"negative"})},
    "Reputation: The Sons of Hodir (Unfriendly)": {"expansion": frozenset({"wotlk"}), "rank_tier": frozenset({"negative"})},
    "Reputation: The Sons of Hodir (Neutral)": {"expansion": frozenset({"wotlk"}), "rank_tier": frozenset({"standard"})},
    "Reputation: The Sons of Hodir (Friendly)": {"expansion": frozenset({"wotlk"}), "rank_tier": frozenset({"standard"})},
    "Reputation: The Sons of Hodir (Honored)": {"expansion": frozenset({"wotlk"}), "rank_tier": frozenset({"standard"})},
    "Reputation: The Sons of Hodir (Revered)": {"expansion": frozenset({"wotlk"}), "rank_tier": frozenset({"standard"})},
    "Reputation: The Sons of Hodir (Exalted)": {"expansion": frozenset({"wotlk"}), "rank_tier": frozenset({"standard"})},
    "Reputation: The Sunreavers (Friendly)": {"expansion": frozenset({"wotlk"}), "rank_tier": frozenset({"standard"})},
    "Reputation: The Sunreavers (Honored)": {"expansion": frozenset({"wotlk"}), "rank_tier": frozenset({"standard"})},
    "Reputation: The Sunreavers (Revered)": {"expansion": frozenset({"wotlk"}), "rank_tier": frozenset({"standard"})},
    "Reputation: The Sunreavers (Exalted)": {"expansion": frozenset({"wotlk"}), "rank_tier": frozenset({"standard"})},
    "Reputation: The Frostborn (Friendly)": {"expansion": frozenset({"wotlk"}), "rank_tier": frozenset({"standard"})},
    "Reputation: The Frostborn (Honored)": {"expansion": frozenset({"wotlk"}), "rank_tier": frozenset({"standard"})},
    "Reputation: The Frostborn (Revered)": {"expansion": frozenset({"wotlk"}), "rank_tier": frozenset({"standard"})},
    "Reputation: The Frostborn (Exalted)": {"expansion": frozenset({"wotlk"}), "rank_tier": frozenset({"standard"})},
    "Reputation: The Ashen Verdict (Friendly)": {"expansion": frozenset({"wotlk"}), "rank_tier": frozenset({"standard"})},
    "Reputation: The Ashen Verdict (Honored)": {"expansion": frozenset({"wotlk"}), "rank_tier": frozenset({"standard"})},
    "Reputation: The Ashen Verdict (Revered)": {"expansion": frozenset({"wotlk"}), "rank_tier": frozenset({"standard"})},
    "Reputation: The Ashen Verdict (Exalted)": {"expansion": frozenset({"wotlk"}), "rank_tier": frozenset({"standard"})},
}
